-- Add evolved, true form, and ultra form name columns to Unit table
-- Then populate from BCU game data (en-UnitName.txt)
-- Also fix formCount for units that don't have 3 forms

-- Add new columns
ALTER TABLE "Unit" ADD COLUMN "evolvedName" TEXT;
ALTER TABLE "Unit" ADD COLUMN "trueName" TEXT;
ALTER TABLE "Unit" ADD COLUMN "ultraName" TEXT;

-- Populate form names from BCU data
UPDATE "Unit" SET "evolvedName" = 'Macho Cat', "trueName" = 'Mohawk Cat' WHERE "unitNumber" = 0;
UPDATE "Unit" SET "evolvedName" = 'Wall Cat', "trueName" = 'Eraser Cat' WHERE "unitNumber" = 1;
UPDATE "Unit" SET "evolvedName" = 'Brave Cat', "trueName" = 'Dark Cat' WHERE "unitNumber" = 2;
UPDATE "Unit" SET "evolvedName" = 'Sexy Legs Cat', "trueName" = 'Macho Leg Cat' WHERE "unitNumber" = 3;
UPDATE "Unit" SET "evolvedName" = 'Giraffe Cat', "trueName" = 'Lion Cat' WHERE "unitNumber" = 4;
UPDATE "Unit" SET "evolvedName" = 'UFO Cat', "trueName" = 'The Flying Cat' WHERE "unitNumber" = 5;
UPDATE "Unit" SET "evolvedName" = 'Whale Cat', "trueName" = 'Island Cat' WHERE "unitNumber" = 6;
UPDATE "Unit" SET "evolvedName" = 'Dragon Cat', "trueName" = 'King Dragon Cat' WHERE "unitNumber" = 7;
UPDATE "Unit" SET "evolvedName" = 'Mythical Titan Cat', "trueName" = 'Jamiera Cat' WHERE "unitNumber" = 8;
UPDATE "Unit" SET "evolvedName" = 'Mother Cat', "trueName" = 'Beefcake Cat' WHERE "unitNumber" = 9;
UPDATE "Unit" SET "evolvedName" = 'Drunken Master Cat', "trueName" = 'Dancer Cat' WHERE "unitNumber" = 10;
UPDATE "Unit" SET "evolvedName" = 'Super Mr.', "trueName" = 'Hyper Mr.' WHERE "unitNumber" = 11;
UPDATE "Unit" SET "evolvedName" = 'Bondage CatNEO', "trueName" = 'Ultimate Bondage Cat' WHERE "unitNumber" = 12;
UPDATE "Unit" SET "evolvedName" = 'Executioner', "trueName" = 'Dark Lazer' WHERE "unitNumber" = 13;
UPDATE "Unit" SET "evolvedName" = 'Cat Gang', "trueName" = 'Heavy Assault C.A.T.' WHERE "unitNumber" = 14;
UPDATE "Unit" SET "evolvedName" = 'Leaf Cat', "trueName" = 'Lollycat' WHERE "unitNumber" = 15;
UPDATE "Unit" SET "evolvedName" = 'Miss MONEKO', "trueName" = 'Superstar MONEKO' WHERE "unitNumber" = 16;
UPDATE "Unit" SET "evolvedName" = 'Biker Cat', "trueName" = 'Unicycle Cat' WHERE "unitNumber" = 17;
UPDATE "Unit" SET "evolvedName" = 'Ninja Frog Cat', "trueName" = 'Flying Ninja Cat' WHERE "unitNumber" = 18;
UPDATE "Unit" SET "evolvedName" = 'Devil Cat', "trueName" = 'Skelecat' WHERE "unitNumber" = 19;
UPDATE "Unit" SET "evolvedName" = 'Knight Cat', "trueName" = 'Pastry Cat' WHERE "unitNumber" = 20;
UPDATE "Unit" SET "evolvedName" = 'Madame Sumo', "trueName" = 'Riceball Cat' WHERE "unitNumber" = 21;
UPDATE "Unit" SET "evolvedName" = 'Samba Cat', "trueName" = 'Gato Amigo' WHERE "unitNumber" = 22;
UPDATE "Unit" SET "evolvedName" = 'Tights Cat', "trueName" = 'Loincloth Cat' WHERE "unitNumber" = 23;
UPDATE "Unit" SET "evolvedName" = 'True Valkyrie Cat', "trueName" = 'Holy Valkyrie Cat' WHERE "unitNumber" = 24;
UPDATE "Unit" SET "evolvedName" = 'Crazed Bahamut Cat', "trueName" = 'Awakened Bahamut Cat' WHERE "unitNumber" = 25;
UPDATE "Unit" SET "evolvedName" = 'Full color Kerihime', "trueName" = 'Bridal Princess Punt' WHERE "unitNumber" = 26;
UPDATE "Unit" SET "evolvedName" = 'Cat Princess beauty' WHERE "unitNumber" = 27;
UPDATE "Unit" SET "evolvedName" = 'Cramped Cats' WHERE "unitNumber" = 28;
UPDATE "Unit" SET "evolvedName" = 'Luchador Cat' WHERE "unitNumber" = 29;
UPDATE "Unit" SET "evolvedName" = 'Avalokitesvara Cat', "trueName" = 'Tathagata Cat' WHERE "unitNumber" = 30;
UPDATE "Unit" SET "evolvedName" = 'Angry Delinquent Cat', "trueName" = 'Ultra Delinquent Cat' WHERE "unitNumber" = 31;
UPDATE "Unit" SET "evolvedName" = 'Dancing Flasher Cat', "trueName" = 'Can Can Cat' WHERE "unitNumber" = 32;
UPDATE "Unit" SET "evolvedName" = 'Sadako Cat', "trueName" = 'Octopus Cat' WHERE "unitNumber" = 33;
UPDATE "Unit" SET "evolvedName" = 'Unknown Cat', "trueName" = 'Ultralan Pasalan' WHERE "unitNumber" = 34;
UPDATE "Unit" SET "evolvedName" = 'Hacker Cat', "trueName" = 'Cyberpunk Cat' WHERE "unitNumber" = 35;
UPDATE "Unit" SET "evolvedName" = 'Butterfly Cat', "trueName" = 'Fishman Cat' WHERE "unitNumber" = 36;
UPDATE "Unit" SET "evolvedName" = 'Masai Cat', "trueName" = 'Jiangshi Cat' WHERE "unitNumber" = 37;
UPDATE "Unit" SET "evolvedName" = 'Solar Cat', "trueName" = 'Chill Cat' WHERE "unitNumber" = 38;
UPDATE "Unit" SET "evolvedName" = 'Face Cat', "trueName" = 'iCat' WHERE "unitNumber" = 39;
UPDATE "Unit" SET "evolvedName" = 'Sexy Bathtub Cat', "trueName" = 'Luxury Bath Cat' WHERE "unitNumber" = 40;
UPDATE "Unit" SET "evolvedName" = 'Paris Cat', "trueName" = 'Cyborg Cat' WHERE "unitNumber" = 41;
UPDATE "Unit" SET "evolvedName" = 'Ice Queen Cat', "trueName" = 'Ice Crystal Cat' WHERE "unitNumber" = 42;
UPDATE "Unit" SET "evolvedName" = 'Cat Machine Mk 2', "trueName" = 'Cat Machine Mk 3' WHERE "unitNumber" = 43;
UPDATE "Unit" SET "evolvedName" = 'Greater Demon Cat', "trueName" = 'Greater Balrog Cat' WHERE "unitNumber" = 44;
UPDATE "Unit" SET "evolvedName" = 'Geisha Cat' WHERE "unitNumber" = 45;
UPDATE "Unit" SET "evolvedName" = 'Jurassic Cat Sitter', "trueName" = 'Catasaurus' WHERE "unitNumber" = 46;
UPDATE "Unit" SET "evolvedName" = 'Thor Cat', "trueName" = 'Maximum the Fighter' WHERE "unitNumber" = 47;
UPDATE "Unit" SET "evolvedName" = 'Captain Cat', "trueName" = 'Dread Pirate Catley' WHERE "unitNumber" = 48;
UPDATE "Unit" SET "evolvedName" = 'Phantom Thief Cat', "trueName" = 'Goemon Cat' WHERE "unitNumber" = 49;
UPDATE "Unit" SET "evolvedName" = 'Monk Cat', "trueName" = 'Sanzo Cat' WHERE "unitNumber" = 50;
UPDATE "Unit" SET "evolvedName" = 'Fisherman Cat', "trueName" = 'Doctor Cat' WHERE "unitNumber" = 51;
UPDATE "Unit" SET "evolvedName" = 'Necromancer Cat', "trueName" = 'Necro-Dancer Cat' WHERE "unitNumber" = 52;
UPDATE "Unit" SET "evolvedName" = 'Filibuster Cat' WHERE "unitNumber" = 53;
UPDATE "Unit" SET "evolvedName" = 'Sorceress Cat', "trueName" = 'Enchantress Cat' WHERE "unitNumber" = 55;
UPDATE "Unit" SET "evolvedName" = 'Cupid Cat', "trueName" = 'Cataur' WHERE "unitNumber" = 56;
UPDATE "Unit" SET "evolvedName" = 'Berserker Cat', "trueName" = 'Paladin Cat' WHERE "unitNumber" = 57;
UPDATE "Unit" SET "evolvedName" = 'Sword Master Cat', "trueName" = 'Elemental Duelist Cat' WHERE "unitNumber" = 58;
UPDATE "Unit" SET "evolvedName" = 'Baby Cats', "trueName" = 'Cats in the Cradle', "ultraName" = 'Cats in the Stroller' WHERE "unitNumber" = 59;
UPDATE "Unit" SET "evolvedName" = 'Michelangelo Cat', "trueName" = 'Quizmaster Cat' WHERE "unitNumber" = 60;
UPDATE "Unit" SET "evolvedName" = 'Fried Shrimp Cat', "trueName" = 'Roe Cat' WHERE "unitNumber" = 61;
UPDATE "Unit" SET "evolvedName" = 'Vendor Cat' WHERE "unitNumber" = 62;
UPDATE "Unit" SET "evolvedName" = 'Kidnapper Cats', "trueName" = 'Rampage Cats' WHERE "unitNumber" = 63;
UPDATE "Unit" SET "evolvedName" = 'Swordsman Johnny' WHERE "unitNumber" = 64;
UPDATE "Unit" SET "evolvedName" = 'Giraffe Princess' WHERE "unitNumber" = 65;
UPDATE "Unit" SET "evolvedName" = 'Dark PPT48', "trueName" = 'PPT46' WHERE "unitNumber" = 66;
UPDATE "Unit" SET "evolvedName" = 'Li''l Gau Gau', "trueName" = 'Crystal Li''l Gau Gau' WHERE "unitNumber" = 67;
UPDATE "Unit" SET "evolvedName" = 'Reaper 999', "trueName" = 'Judgment' WHERE "unitNumber" = 68;
UPDATE "Unit" SET "evolvedName" = 'Sleeping Beauty Punt II', "trueName" = 'Oversleeping Beauty Punt' WHERE "unitNumber" = 69;
UPDATE "Unit" SET "evolvedName" = 'Grudge Cat', "trueName" = 'Ritual Cat' WHERE "unitNumber" = 70;
UPDATE "Unit" SET "evolvedName" = 'Wargod Yukimura', "trueName" = 'Immortal Yukimura' WHERE "unitNumber" = 71;
UPDATE "Unit" SET "evolvedName" = 'Wargod Keiji', "trueName" = 'Immortal Keiji' WHERE "unitNumber" = 72;
UPDATE "Unit" SET "evolvedName" = 'Wargod Nobunaga', "trueName" = 'Immortal Nobunaga', "ultraName" = 'Phantasmal Nobunaga' WHERE "unitNumber" = 73;
UPDATE "Unit" SET "evolvedName" = 'Sashimi Cat', "trueName" = 'Xmas Pudding Cat' WHERE "unitNumber" = 74;
UPDATE "Unit" SET "evolvedName" = 'Windy, type α', "trueName" = 'Divine Windy', "ultraName" = 'Ultimate Windy' WHERE "unitNumber" = 75;
UPDATE "Unit" SET "evolvedName" = 'Thundia, type β', "trueName" = 'Divine Thundia', "ultraName" = 'Ultimate Thundia' WHERE "unitNumber" = 76;
UPDATE "Unit" SET "evolvedName" = 'Droid Cat Mk 2', "trueName" = 'SpringDroid' WHERE "unitNumber" = 77;
UPDATE "Unit" SET "evolvedName" = 'Major Space Cat', "trueName" = 'Space Marine Cat' WHERE "unitNumber" = 78;
UPDATE "Unit" SET "evolvedName" = 'Sick Cat', "trueName" = 'Prisoner Cat' WHERE "unitNumber" = 79;
UPDATE "Unit" SET "evolvedName" = 'Gentleman Cat', "trueName" = 'Gentleman Bros.' WHERE "unitNumber" = 80;
UPDATE "Unit" SET "evolvedName" = 'Cat-o-tron', "trueName" = 'Nyalladin' WHERE "unitNumber" = 81;
UPDATE "Unit" SET "evolvedName" = 'Orange Shinobi' WHERE "unitNumber" = 82;
UPDATE "Unit" SET "evolvedName" = 'Earth King Sodom', "trueName" = 'God-Emperor Sodom' WHERE "unitNumber" = 83;
UPDATE "Unit" SET "evolvedName" = 'Holy Dragon Megidora', "trueName" = 'God-Emperor Megidora' WHERE "unitNumber" = 84;
UPDATE "Unit" SET "evolvedName" = 'Dragon King Vars', "trueName" = 'God-Emperor Vars' WHERE "unitNumber" = 85;
UPDATE "Unit" SET "evolvedName" = 'God Dragon Kamukura', "trueName" = 'God-Emperor Kamukura' WHERE "unitNumber" = 86;
UPDATE "Unit" SET "evolvedName" = 'Dragonslayer Raiden', "trueName" = 'God-Emperor Raiden' WHERE "unitNumber" = 87;
UPDATE "Unit" SET "evolvedName" = 'Pair Rope Jump Cat', "trueName" = 'Noodle Cats' WHERE "unitNumber" = 88;
UPDATE "Unit" SET "evolvedName" = 'Crazed Macho Cat', "trueName" = 'Manic Mohawk Cat' WHERE "unitNumber" = 91;
UPDATE "Unit" SET "evolvedName" = 'Crazed Wall Cat', "trueName" = 'Manic Eraser Cat' WHERE "unitNumber" = 92;
UPDATE "Unit" SET "evolvedName" = 'Crazed Brave Cat', "trueName" = 'Manic Dark Cat' WHERE "unitNumber" = 93;
UPDATE "Unit" SET "evolvedName" = 'Crazed Sexy Legs Cat', "trueName" = 'Manic Macho Legs' WHERE "unitNumber" = 94;
UPDATE "Unit" SET "evolvedName" = 'Crazed Giraffe Cat', "trueName" = 'Manic Lion Cat' WHERE "unitNumber" = 95;
UPDATE "Unit" SET "evolvedName" = 'Crazed UFO Cat', "trueName" = 'Manic Flying Cat' WHERE "unitNumber" = 96;
UPDATE "Unit" SET "evolvedName" = 'Crazed Whale Cat', "trueName" = 'Manic Island Cat' WHERE "unitNumber" = 97;
UPDATE "Unit" SET "evolvedName" = 'Crazed Dragon Cat', "trueName" = 'Manic King Dragon' WHERE "unitNumber" = 98;
UPDATE "Unit" SET "evolvedName" = 'Crazed M. Titan Cat', "trueName" = 'Manic Jamiera Cat' WHERE "unitNumber" = 99;
UPDATE "Unit" SET "evolvedName" = 'Sportsgirl Cat', "trueName" = 'Wrestling Cat' WHERE "unitNumber" = 100;
UPDATE "Unit" SET "evolvedName" = 'Mega Cat', "trueName" = 'Mega Cat EX' WHERE "unitNumber" = 103;
UPDATE "Unit" SET "evolvedName" = 'Gross Koi Cat', "trueName" = 'Kiss and Koi' WHERE "unitNumber" = 104;
UPDATE "Unit" SET "evolvedName" = 'Kuu, type γ', "trueName" = 'Divine Kuu' WHERE "unitNumber" = 105;
UPDATE "Unit" SET "evolvedName" = 'Kai, type μ', "trueName" = 'Divine Kai' WHERE "unitNumber" = 106;
UPDATE "Unit" SET "evolvedName" = 'Coppermine, type κ', "trueName" = 'Divine Coppermine' WHERE "unitNumber" = 107;
UPDATE "Unit" SET "evolvedName" = 'Secret Base' WHERE "unitNumber" = 108;
UPDATE "Unit" SET "evolvedName" = 'Madam King', "trueName" = 'Madam the Savannah' WHERE "unitNumber" = 109;
UPDATE "Unit" SET "evolvedName" = 'Celesse CC' WHERE "unitNumber" = 110;
UPDATE "Unit" SET "evolvedName" = 'Nono CC', "trueName" = 'Frolicking Nono CC' WHERE "unitNumber" = 111;
UPDATE "Unit" SET "evolvedName" = 'Olga CC' WHERE "unitNumber" = 112;
UPDATE "Unit" SET "evolvedName" = 'Norn CC' WHERE "unitNumber" = 113;
UPDATE "Unit" SET "evolvedName" = 'Yoichi CC' WHERE "unitNumber" = 114;
UPDATE "Unit" SET "evolvedName" = 'Serum CC' WHERE "unitNumber" = 115;
UPDATE "Unit" SET "evolvedName" = 'Fuu CC' WHERE "unitNumber" = 116;
UPDATE "Unit" SET "evolvedName" = 'Aura CC' WHERE "unitNumber" = 117;
UPDATE "Unit" SET "evolvedName" = 'Rei CC' WHERE "unitNumber" = 118;
UPDATE "Unit" SET "evolvedName" = 'Wyvern Cat', "trueName" = 'Wyvern and Alec' WHERE "unitNumber" = 119;
UPDATE "Unit" SET "evolvedName" = 'Healer CC', "trueName" = 'Healer Cat CC' WHERE "unitNumber" = 120;
UPDATE "Unit" SET "evolvedName" = 'Merc CC', "trueName" = 'Merc & Cat CC' WHERE "unitNumber" = 121;
UPDATE "Unit" SET "evolvedName" = 'Office Lady Cat', "trueName" = 'Call Center Cat' WHERE "unitNumber" = 122;
UPDATE "Unit" SET "evolvedName" = 'Brah Cats', "trueName" = 'Val Val Cat' WHERE "unitNumber" = 123;
UPDATE "Unit" SET "evolvedName" = 'Wargod Masamune', "trueName" = 'Immortal Masamune' WHERE "unitNumber" = 124;
UPDATE "Unit" SET "evolvedName" = 'Wargod Shingen', "trueName" = 'Immortal Shingen' WHERE "unitNumber" = 125;
UPDATE "Unit" SET "evolvedName" = 'Puppetmaster Cat', "trueName" = 'Puppetmaster & Charley' WHERE "unitNumber" = 126;
UPDATE "Unit" SET "evolvedName" = 'Cooldown Cat', "trueName" = 'Bombercat' WHERE "unitNumber" = 127;
UPDATE "Unit" SET "evolvedName" = 'Groucho Cat', "trueName" = 'Kite Cat' WHERE "unitNumber" = 128;
UPDATE "Unit" SET "evolvedName" = 'Gold Macho Cat', "trueName" = 'Glittering Macho Cat' WHERE "unitNumber" = 129;
UPDATE "Unit" SET "evolvedName" = 'Ururun Cat', "trueName" = 'Awakened Ururun' WHERE "unitNumber" = 130;
UPDATE "Unit" SET "evolvedName" = 'Miss NENEKO' WHERE "unitNumber" = 131;
UPDATE "Unit" SET "evolvedName" = 'Drunken Master Cat X', "trueName" = 'Iron Claw X' WHERE "unitNumber" = 132;
UPDATE "Unit" SET "evolvedName" = 'Guardian Gamereon', "trueName" = 'King Gamereon' WHERE "unitNumber" = 134;
UPDATE "Unit" SET "evolvedName" = 'Super Galaxy Cosmo', "trueName" = 'Ultima Galaxy Cosmo', "ultraName" = 'Supernova Cosmo' WHERE "unitNumber" = 135;
UPDATE "Unit" SET "evolvedName" = 'The Peach Angels', "trueName" = 'The Peach Devils' WHERE "unitNumber" = 136;
UPDATE "Unit" SET "evolvedName" = 'Jizo''s Moving Castle', "trueName" = 'Jizo''s Mega-Castle', "ultraName" = 'Ultra Kasa Jizo' WHERE "unitNumber" = 137;
UPDATE "Unit" SET "evolvedName" = 'The Death Moon', "trueName" = 'The Chaos Moon', "ultraName" = 'Ultra Kaguya' WHERE "unitNumber" = 138;
UPDATE "Unit" SET "evolvedName" = 'Muscleman Cat' WHERE "unitNumber" = 140;
UPDATE "Unit" SET "evolvedName" = 'Secret God' WHERE "unitNumber" = 141;
UPDATE "Unit" SET "evolvedName" = 'Heartful Nurse Cat', "trueName" = 'Joyful Nurse Cat' WHERE "unitNumber" = 143;
UPDATE "Unit" SET "evolvedName" = 'Cat Base Jr.', "trueName" = 'Cat Base Ultra' WHERE "unitNumber" = 144;
UPDATE "Unit" SET "evolvedName" = 'Cat Eastwood', "trueName" = 'Rodeo Cat' WHERE "unitNumber" = 145;
UPDATE "Unit" SET "evolvedName" = 'Totem Cat', "trueName" = 'Acrobat Cats' WHERE "unitNumber" = 146;
UPDATE "Unit" SET "evolvedName" = 'Plane Cat', "trueName" = 'Robocat' WHERE "unitNumber" = 147;
UPDATE "Unit" SET "evolvedName" = 'Artist Cat', "trueName" = 'Ramen Cat' WHERE "unitNumber" = 148;
UPDATE "Unit" SET "evolvedName" = 'Commando Cat', "trueName" = 'Cameraman Cat' WHERE "unitNumber" = 149;
UPDATE "Unit" SET "evolvedName" = 'Princess Juliet Cat', "trueName" = 'Juliet the Maiko' WHERE "unitNumber" = 150;
UPDATE "Unit" SET "evolvedName" = 'Ring Girl Cat', "trueName" = 'Pizza Cat' WHERE "unitNumber" = 151;
UPDATE "Unit" SET "evolvedName" = 'Drama Cats', "trueName" = 'Slapstick Cats' WHERE "unitNumber" = 152;
UPDATE "Unit" SET "evolvedName" = 'Cat Projector', "trueName" = 'Catophone' WHERE "unitNumber" = 153;
UPDATE "Unit" SET "evolvedName" = 'Showoff Cat', "trueName" = 'Hoopmaster Cat' WHERE "unitNumber" = 154;
UPDATE "Unit" SET "evolvedName" = 'Wargod Kenshin', "trueName" = 'Immortal Kenshin', "ultraName" = 'Hellrider Kenshin' WHERE "unitNumber" = 158;
UPDATE "Unit" SET "evolvedName" = 'Kalisa, type χ', "trueName" = 'Divine Kalisa' WHERE "unitNumber" = 159;
UPDATE "Unit" SET "evolvedName" = 'Phoenix Yurinchi', "trueName" = 'Gekirinchi' WHERE "unitNumber" = 160;
UPDATE "Unit" SET "evolvedName" = 'Crazed Princess Punt CC', "trueName" = 'Manic Princess Punt' WHERE "unitNumber" = 161;
UPDATE "Unit" SET "evolvedName" = 'Asilan Pasalan', "trueName" = 'Assassinlan Pasalan' WHERE "unitNumber" = 168;
UPDATE "Unit" SET "evolvedName" = 'Kubilan Pasalan', "trueName" = 'E. Kubilan Pasalan' WHERE "unitNumber" = 169;
UPDATE "Unit" SET "evolvedName" = 'Tesalan Pasalan', "trueName" = 'Lufalan Pasalan' WHERE "unitNumber" = 170;
UPDATE "Unit" SET "evolvedName" = 'Balalan Pasalan', "trueName" = 'Piccolan Pasalan' WHERE "unitNumber" = 171;
UPDATE "Unit" SET "evolvedName" = 'Dark Emperor Catdam', "trueName" = 'Schoolbus Nyandam' WHERE "unitNumber" = 172;
UPDATE "Unit" SET "evolvedName" = 'Young Man Mola', "trueName" = 'Citizen Mola' WHERE "unitNumber" = 173;
UPDATE "Unit" SET "evolvedName" = 'Living Legend', "trueName" = 'Master of the Pacific' WHERE "unitNumber" = 174;
UPDATE "Unit" SET "evolvedName" = 'Catorpedo' WHERE "unitNumber" = 175;
UPDATE "Unit" SET "evolvedName" = 'Creepmallow' WHERE "unitNumber" = 176;
UPDATE "Unit" SET "evolvedName" = 'Archdragon Dioramos', "trueName" = 'God-Emperor Dioramos', "ultraName" = 'Ascendant Dioramos' WHERE "unitNumber" = 177;
UPDATE "Unit" SET "evolvedName" = 'Takuya, Yuki ＆ Cat', "trueName" = 'Takuya＆ Lovely Yuki' WHERE "unitNumber" = 179;
UPDATE "Unit" SET "evolvedName" = 'Mystery Yuki ＆ Cat', "trueName" = 'Mystery Catgirl Yuki' WHERE "unitNumber" = 180;
UPDATE "Unit" SET "evolvedName" = 'Lovely Yuki Cat' WHERE "unitNumber" = 181;
UPDATE "Unit" SET "evolvedName" = 'Cat Kart G', "trueName" = 'Cat Kart P' WHERE "unitNumber" = 183;
UPDATE "Unit" SET "evolvedName" = 'Mint' WHERE "unitNumber" = 184;
UPDATE "Unit" SET "evolvedName" = 'Hearscht CC', "trueName" = 'Revolutionary Hearscht CC' WHERE "unitNumber" = 185;
UPDATE "Unit" SET "evolvedName" = 'Cornelia CC' WHERE "unitNumber" = 186;
UPDATE "Unit" SET "evolvedName" = 'Juvens CC', "trueName" = 'Holiday Juvens CC' WHERE "unitNumber" = 187;
UPDATE "Unit" SET "evolvedName" = 'Mystica CC', "trueName" = 'Savior Mystica CC' WHERE "unitNumber" = 188;
UPDATE "Unit" SET "evolvedName" = 'Alois CC' WHERE "unitNumber" = 189;
UPDATE "Unit" SET "evolvedName" = 'Citrouille CC' WHERE "unitNumber" = 190;
UPDATE "Unit" SET "evolvedName" = 'Titi CC', "trueName" = 'Titi Cat CC' WHERE "unitNumber" = 191;
UPDATE "Unit" SET "evolvedName" = 'Shadow Akira', "trueName" = 'Inferno Akira' WHERE "unitNumber" = 194;
UPDATE "Unit" SET "evolvedName" = 'Dr. Mekako', "trueName" = 'Mission Control Mekako' WHERE "unitNumber" = 195;
UPDATE "Unit" SET "evolvedName" = 'Dark Catman', "trueName" = 'Ultimate Catman' WHERE "unitNumber" = 196;
UPDATE "Unit" SET "evolvedName" = 'Neo Psychocat', "trueName" = 'Corrupted Psychocat' WHERE "unitNumber" = 197;
UPDATE "Unit" SET "evolvedName" = 'Magica Cat', "trueName" = 'Thaumaturge Cat' WHERE "unitNumber" = 198;
UPDATE "Unit" SET "evolvedName" = 'Castaway Cat', "trueName" = 'Seafarer Cat' WHERE "unitNumber" = 199;
UPDATE "Unit" SET "evolvedName" = 'Metal Macho' WHERE "unitNumber" = 200;
UPDATE "Unit" SET "evolvedName" = 'Banner Cat', "trueName" = 'Mochi Cat' WHERE "unitNumber" = 201;
UPDATE "Unit" SET "evolvedName" = 'Big Baozi' WHERE "unitNumber" = 202;
UPDATE "Unit" SET "evolvedName" = 'Fire Squad Kachiyama', "trueName" = 'Kachiyama Assault Brigade' WHERE "unitNumber" = 203;
UPDATE "Unit" SET "evolvedName" = 'Li''l Macho Cat', "trueName" = 'Li''l Mohawk Cat' WHERE "unitNumber" = 209;
UPDATE "Unit" SET "evolvedName" = 'Li''l Wall Cat', "trueName" = 'Li''l Eraser Cat' WHERE "unitNumber" = 210;
UPDATE "Unit" SET "evolvedName" = 'Li''l Brave Cat', "trueName" = 'Li''l Dark Cat' WHERE "unitNumber" = 211;
UPDATE "Unit" SET "evolvedName" = 'The Black Cat', "trueName" = 'The Grey Fox', "ultraName" = 'The Spectral Cat' WHERE "unitNumber" = 212;
UPDATE "Unit" SET "evolvedName" = 'Cat Royale', "trueName" = 'Value Meal Cat' WHERE "unitNumber" = 213;
UPDATE "Unit" SET "evolvedName" = 'HYAKUTARO CC' WHERE "unitNumber" = 214;
UPDATE "Unit" SET "evolvedName" = 'MARCO CC' WHERE "unitNumber" = 215;
UPDATE "Unit" SET "evolvedName" = 'TARMA CC' WHERE "unitNumber" = 216;
UPDATE "Unit" SET "evolvedName" = 'ERI CC' WHERE "unitNumber" = 217;
UPDATE "Unit" SET "evolvedName" = 'FIO CC' WHERE "unitNumber" = 218;
UPDATE "Unit" SET "evolvedName" = 'SV-001 CC' WHERE "unitNumber" = 219;
UPDATE "Unit" SET "evolvedName" = 'ALLEN O''NEIL CC' WHERE "unitNumber" = 220;
UPDATE "Unit" SET "evolvedName" = 'MARS PEOPLE CC' WHERE "unitNumber" = 221;
UPDATE "Unit" SET "evolvedName" = 'HUGE HERMIT CC', "trueName" = 'GOLDEN HUGE HERMIT CC' WHERE "unitNumber" = 222;
UPDATE "Unit" SET "evolvedName" = 'JUPITER KING CC', "trueName" = 'GOLDEN JUPITER CC' WHERE "unitNumber" = 223;
UPDATE "Unit" SET "evolvedName" = 'GENERAL MORDEN', "trueName" = 'GOLDEN MORDEN CC' WHERE "unitNumber" = 224;
UPDATE "Unit" SET "evolvedName" = 'HI-DO CC', "trueName" = 'HI-DO MK III' WHERE "unitNumber" = 225;
UPDATE "Unit" SET "evolvedName" = 'Dark Merchant Babil', "trueName" = 'Mad Doctor Klay' WHERE "unitNumber" = 226;
UPDATE "Unit" SET "evolvedName" = 'Cat O''Lantern', "trueName" = 'Harbinger Cat' WHERE "unitNumber" = 227;
UPDATE "Unit" SET "evolvedName" = 'Witchy Neneko', "trueName" = 'Costumed Witchy Neneko' WHERE "unitNumber" = 228;
UPDATE "Unit" SET "evolvedName" = 'Hallowindy, type α' WHERE "unitNumber" = 229;
UPDATE "Unit" SET "evolvedName" = 'Spooky Thundia, type β' WHERE "unitNumber" = 230;
UPDATE "Unit" SET "evolvedName" = 'Prof. Cat Jobs', "trueName" = 'Headmaster Cat Jobs' WHERE "unitNumber" = 237;
UPDATE "Unit" SET "evolvedName" = 'Rich Cat Sr.', "trueName" = 'Richest Cat' WHERE "unitNumber" = 238;
UPDATE "Unit" SET "evolvedName" = 'Sniper the Heavy', "trueName" = 'Sniper the Deadeye' WHERE "unitNumber" = 239;
UPDATE "Unit" SET "evolvedName" = 'Togelan Pasalan', "trueName" = 'Shishilan Pasalan' WHERE "unitNumber" = 240;
UPDATE "Unit" SET "evolvedName" = 'Frosty Kai, type μ', "trueName" = 'Frostspirit Kai, type μ' WHERE "unitNumber" = 241;
UPDATE "Unit" SET "evolvedName" = 'Santa Kuu, type γ' WHERE "unitNumber" = 242;
UPDATE "Unit" SET "evolvedName" = 'Holy Coppermine, type κ' WHERE "unitNumber" = 243;
UPDATE "Unit" SET "evolvedName" = 'Cat''s Gift' WHERE "unitNumber" = 244;
UPDATE "Unit" SET "evolvedName" = 'Li''l Sexy Legs Cat', "trueName" = 'Li''l Macho Legs Cat' WHERE "unitNumber" = 245;
UPDATE "Unit" SET "evolvedName" = 'Li''l Giraffe Cat', "trueName" = 'Li''l Lion Cat' WHERE "unitNumber" = 246;
UPDATE "Unit" SET "evolvedName" = 'Li''l UFO Cat', "trueName" = 'Li''l Flying Cat' WHERE "unitNumber" = 247;
UPDATE "Unit" SET "evolvedName" = 'Bake-Nyanko', "trueName" = 'Extra-Life Cat' WHERE "unitNumber" = 248;
UPDATE "Unit" SET "evolvedName" = 'The Majestic Zeus', "trueName" = 'Almighty Zeus' WHERE "unitNumber" = 257;
UPDATE "Unit" SET "evolvedName" = 'Anubis the Unblemished', "trueName" = 'Almighty Anubis' WHERE "unitNumber" = 258;
UPDATE "Unit" SET "evolvedName" = 'Megaphrodite', "trueName" = 'Almighty Aphrodite' WHERE "unitNumber" = 259;
UPDATE "Unit" SET "evolvedName" = 'Drone Cat', "trueName" = 'Time Traveller Cat' WHERE "unitNumber" = 260;
UPDATE "Unit" SET "evolvedName" = 'Oni Hayabusa', "trueName" = 'Akuma Hayabusa' WHERE "unitNumber" = 261;
UPDATE "Unit" SET "evolvedName" = 'Hurricat', "trueName" = 'Catyphoon' WHERE "unitNumber" = 267;
UPDATE "Unit" SET "evolvedName" = 'Crimson Mina', "trueName" = 'Awakened Mina' WHERE "unitNumber" = 268;
UPDATE "Unit" SET "evolvedName" = 'Mighty Lord Gao' WHERE "unitNumber" = 269;
UPDATE "Unit" SET "evolvedName" = 'Crazed Yuki & Cat', "trueName" = 'Crazed Catgirl Yuki' WHERE "unitNumber" = 270;
UPDATE "Unit" SET "evolvedName" = 'Glorious Amaterasu', "trueName" = 'Almighty Amaterasu' WHERE "unitNumber" = 271;
UPDATE "Unit" SET "evolvedName" = 'Exalted Ganesha', "trueName" = 'Almighty Ganesha' WHERE "unitNumber" = 272;
UPDATE "Unit" SET "evolvedName" = 'Waitress Cat', "trueName" = 'Soba Cat' WHERE "unitNumber" = 273;
UPDATE "Unit" SET "evolvedName" = 'Tropical Kalisa, type X' WHERE "unitNumber" = 274;
UPDATE "Unit" SET "evolvedName" = 'Midsummer Cat', "trueName" = 'Brightsummer Cat' WHERE "unitNumber" = 275;
UPDATE "Unit" SET "evolvedName" = 'Seaside Neneko', "trueName" = 'Early Summer Neneko' WHERE "unitNumber" = 276;
UPDATE "Unit" SET "evolvedName" = 'Funghi ''n'' Cat' WHERE "unitNumber" = 277;
UPDATE "Unit" SET "evolvedName" = 'Tanky ''n'' Cat' WHERE "unitNumber" = 278;
UPDATE "Unit" SET "evolvedName" = 'Gross White Cat' WHERE "unitNumber" = 279;
UPDATE "Unit" SET "evolvedName" = 'Castley' WHERE "unitNumber" = 280;
UPDATE "Unit" SET "evolvedName" = 'So-Ran Cat', "trueName" = 'Gorgeous Groovin'' Cat' WHERE "unitNumber" = 282;
UPDATE "Unit" SET "evolvedName" = 'Pai-Pai Z', "trueName" = 'Pai-Pai DX' WHERE "unitNumber" = 283;
UPDATE "Unit" SET "evolvedName" = 'Maglev Cat', "trueName" = 'Bullet Train Cat' WHERE "unitNumber" = 284;
UPDATE "Unit" SET "evolvedName" = 'Assault Unit R.E.I.', "trueName" = 'Flight Unit R.E.I.' WHERE "unitNumber" = 286;
UPDATE "Unit" SET "evolvedName" = 'Major Leaguer Cat', "trueName" = 'Golfer Cat' WHERE "unitNumber" = 287;
UPDATE "Unit" SET "evolvedName" = 'Madoka & Cat', "trueName" = 'Ultimate Madoka' WHERE "unitNumber" = 288;
UPDATE "Unit" SET "evolvedName" = 'Homura & Cat', "trueName" = 'Devil Homura' WHERE "unitNumber" = 289;
UPDATE "Unit" SET "evolvedName" = 'Sayaka & Cat' WHERE "unitNumber" = 290;
UPDATE "Unit" SET "evolvedName" = 'Mami & Cat' WHERE "unitNumber" = 291;
UPDATE "Unit" SET "evolvedName" = 'Kyoko & Cat' WHERE "unitNumber" = 292;
UPDATE "Unit" SET "evolvedName" = 'Kyubey & Cat' WHERE "unitNumber" = 293;
UPDATE "Unit" SET "evolvedName" = 'Magical Girl Madoka Cat' WHERE "unitNumber" = 294;
UPDATE "Unit" SET "evolvedName" = 'Magical Girl Homura Cat' WHERE "unitNumber" = 295;
UPDATE "Unit" SET "evolvedName" = 'Magical Girl Sayaka Cat' WHERE "unitNumber" = 296;
UPDATE "Unit" SET "evolvedName" = 'Magical Girl Mami Cat' WHERE "unitNumber" = 297;
UPDATE "Unit" SET "evolvedName" = 'Magical Girl Kyoko Cat' WHERE "unitNumber" = 298;
UPDATE "Unit" SET "evolvedName" = 'Li''l Magical Girl Madoka', "trueName" = 'Li''l Ultimate Madoka' WHERE "unitNumber" = 299;
UPDATE "Unit" SET "evolvedName" = 'Li''l Magical Girl Homura', "trueName" = 'Li''l Devil Homura' WHERE "unitNumber" = 300;
UPDATE "Unit" SET "evolvedName" = 'Tank Kyubey Cat' WHERE "unitNumber" = 301;
UPDATE "Unit" SET "evolvedName" = 'Succubus Cat', "trueName" = 'Queen Succubus Cat' WHERE "unitNumber" = 302;
UPDATE "Unit" SET "evolvedName" = 'Delivery Cat', "trueName" = 'Cafeteria Cat' WHERE "unitNumber" = 303;
UPDATE "Unit" SET "evolvedName" = 'CAT-6 Siege Engine', "trueName" = 'CAT-8 Behemoth', "ultraName" = 'CAT-10 Gigapult' WHERE "unitNumber" = 304;
UPDATE "Unit" SET "evolvedName" = 'B.C.S. Lionheart', "trueName" = 'B.C.S. Tigerclaw', "ultraName" = 'B.C.S. Beartooth' WHERE "unitNumber" = 305;
UPDATE "Unit" SET "evolvedName" = 'NEK-0 Sky Fortress', "trueName" = 'NEK-02 Air Citadel', "ultraName" = 'NEK-03 Cloud Emperor' WHERE "unitNumber" = 306;
UPDATE "Unit" SET "evolvedName" = 'Polevaulter Cat', "trueName" = 'Housewife Cat' WHERE "unitNumber" = 307;
UPDATE "Unit" SET "evolvedName" = 'Lumbercat', "trueName" = 'Weedwacker Cat' WHERE "unitNumber" = 308;
UPDATE "Unit" SET "evolvedName" = 'Yule Knight Nurse', "trueName" = 'Xmas Spirit Nurse' WHERE "unitNumber" = 310;
UPDATE "Unit" SET "evolvedName" = 'Li''l Whale Cat', "trueName" = 'Li''l Island Cat' WHERE "unitNumber" = 311;
UPDATE "Unit" SET "evolvedName" = 'Li''l Dragon Cat', "trueName" = 'Li''l King Dragon Cat' WHERE "unitNumber" = 312;
UPDATE "Unit" SET "evolvedName" = 'Li''l Mythical Titan', "trueName" = 'Li''l Jamiera Cat' WHERE "unitNumber" = 313;
UPDATE "Unit" SET "evolvedName" = 'New Year Neneko', "trueName" = 'Festive New Year Neneko' WHERE "unitNumber" = 314;
UPDATE "Unit" SET "evolvedName" = 'NEKOTARO' WHERE "unitNumber" = 315;
UPDATE "Unit" SET "evolvedName" = 'Valiant Poseidon', "trueName" = 'Almighty Poseidon' WHERE "unitNumber" = 316;
UPDATE "Unit" SET "evolvedName" = 'PPAP' WHERE "unitNumber" = 317;
UPDATE "Unit" SET "evolvedName" = 'Mitama the Oracle' WHERE "unitNumber" = 318;
UPDATE "Unit" SET "evolvedName" = 'True Killer Cat', "trueName" = 'Radical Cat' WHERE "unitNumber" = 319;
UPDATE "Unit" SET "evolvedName" = 'Rock Revengers', "trueName" = 'The One-Hit Wonders' WHERE "unitNumber" = 322;
UPDATE "Unit" SET "evolvedName" = 'Heroic Musashi', "trueName" = 'Awakened Musashi' WHERE "unitNumber" = 323;
UPDATE "Unit" SET "evolvedName" = 'Cleanerbot Cat', "trueName" = 'Green Shell Cat' WHERE "unitNumber" = 324;
UPDATE "Unit" SET "evolvedName" = 'Heavyweight Cat', "trueName" = 'Ectoweight Cat' WHERE "unitNumber" = 325;
UPDATE "Unit" SET "evolvedName" = 'Miraculous Mobius' WHERE "unitNumber" = 326;
UPDATE "Unit" SET "evolvedName" = 'Reckless Belial' WHERE "unitNumber" = 327;
UPDATE "Unit" SET "evolvedName" = 'Heartful Happy 100' WHERE "unitNumber" = 328;
UPDATE "Unit" SET "evolvedName" = 'Easter Cat', "trueName" = 'Easter Egg Cat' WHERE "unitNumber" = 329;
UPDATE "Unit" SET "evolvedName" = 'Full-Bloom Kenshin', "trueName" = 'Spring Breeze Kenshin' WHERE "unitNumber" = 330;
UPDATE "Unit" SET "evolvedName" = 'Disciple Psychoduck', "trueName" = 'Malevolent Mad-Duck' WHERE "unitNumber" = 331;
UPDATE "Unit" SET "evolvedName" = 'Hoppity Neneko', "trueName" = 'Blossoming Neneko' WHERE "unitNumber" = 332;
UPDATE "Unit" SET "evolvedName" = 'Diabolic Gao' WHERE "unitNumber" = 333;
UPDATE "Unit" SET "evolvedName" = 'Himeyuri Ninetails', "trueName" = 'Fox Queen Himeyuri' WHERE "unitNumber" = 334;
UPDATE "Unit" SET "evolvedName" = 'Sea Mistress Ruri', "trueName" = 'Mer-Queen Ruri' WHERE "unitNumber" = 335;
UPDATE "Unit" SET "evolvedName" = 'Pharaoh Reika', "trueName" = 'Eternal Reika' WHERE "unitNumber" = 336;
UPDATE "Unit" SET "evolvedName" = 'HMS Princess CC', "trueName" = 'HMS Princess II CC' WHERE "unitNumber" = 337;
UPDATE "Unit" SET "evolvedName" = 'Wargod Yoshimoto', "trueName" = 'Immortal Yoshimoto' WHERE "unitNumber" = 338;
UPDATE "Unit" SET "evolvedName" = 'Redhead Lovely Yuki Cat', "trueName" = 'Redhead Muscled Yuki Cat' WHERE "unitNumber" = 340;
UPDATE "Unit" SET "evolvedName" = 'Lost World Yuki ＆ Cat', "trueName" = 'Lost World Catgirl Yuki' WHERE "unitNumber" = 341;
UPDATE "Unit" SET "evolvedName" = 'Neo Maneki Cat' WHERE "unitNumber" = 342;
UPDATE "Unit" SET "evolvedName" = 'Slugcat' WHERE "unitNumber" = 343;
UPDATE "Unit" SET "evolvedName" = 'Orthos CC', "trueName" = 'Artist Orthos CC' WHERE "unitNumber" = 344;
UPDATE "Unit" SET "evolvedName" = 'Michelia CC', "trueName" = 'Naptime Michelia CC' WHERE "unitNumber" = 345;
UPDATE "Unit" SET "evolvedName" = 'Todomeki CC' WHERE "unitNumber" = 346;
UPDATE "Unit" SET "evolvedName" = 'Twinstars, type Φ', "trueName" = 'Divine Twinstars' WHERE "unitNumber" = 351;
UPDATE "Unit" SET "evolvedName" = 'Grandmaster Cat', "trueName" = 'Masked Grandmaster Cat' WHERE "unitNumber" = 352;
UPDATE "Unit" SET "evolvedName" = 'Seashore Kai, type μ' WHERE "unitNumber" = 354;
UPDATE "Unit" SET "evolvedName" = 'Orbital Platform Armageddon', "trueName" = 'Orbital Annihilator Ragnarok' WHERE "unitNumber" = 355;
UPDATE "Unit" SET "evolvedName" = 'Wolf Princess Deale', "trueName" = 'Jester Queen Deale' WHERE "unitNumber" = 357;
UPDATE "Unit" SET "evolvedName" = 'Verbena the Bride', "trueName" = 'Opulent Verbena' WHERE "unitNumber" = 358;
UPDATE "Unit" SET "evolvedName" = 'Bazibon', "trueName" = 'Bazibastra', "ultraName" = 'Bazifenix' WHERE "unitNumber" = 359;
UPDATE "Unit" SET "evolvedName" = 'Marinmizu', "trueName" = 'Mizuririn', "ultraName" = 'Mizunade' WHERE "unitNumber" = 360;
UPDATE "Unit" SET "evolvedName" = 'Erphuan', "trueName" = 'Aervanta', "ultraName" = 'Aervantex' WHERE "unitNumber" = 361;
UPDATE "Unit" SET "evolvedName" = 'Saber CC', "trueName" = 'Saber Alter CC' WHERE "unitNumber" = 362;
UPDATE "Unit" SET "evolvedName" = 'Rin Tohsaka CC' WHERE "unitNumber" = 363;
UPDATE "Unit" SET "evolvedName" = 'Illyasviel CC' WHERE "unitNumber" = 364;
UPDATE "Unit" SET "evolvedName" = 'Archer CC' WHERE "unitNumber" = 365;
UPDATE "Unit" SET "evolvedName" = 'Lancer CC' WHERE "unitNumber" = 366;
UPDATE "Unit" SET "evolvedName" = 'Rider CC' WHERE "unitNumber" = 367;
UPDATE "Unit" SET "evolvedName" = 'Gilgamesh CC' WHERE "unitNumber" = 368;
UPDATE "Unit" SET "evolvedName" = 'Heroic Spirit Saber Cat', "trueName" = 'Saber Alter Cat' WHERE "unitNumber" = 369;
UPDATE "Unit" SET "evolvedName" = 'Apron Sakura Cat', "trueName" = 'Dreaming Sakura Cat' WHERE "unitNumber" = 370;
UPDATE "Unit" SET "evolvedName" = 'Mage Rin Cat' WHERE "unitNumber" = 371;
UPDATE "Unit" SET "evolvedName" = 'Snow Faerie Illya' WHERE "unitNumber" = 372;
UPDATE "Unit" SET "evolvedName" = 'Li''l Shirou CC' WHERE "unitNumber" = 373;
UPDATE "Unit" SET "evolvedName" = 'Li''l Sakura CC' WHERE "unitNumber" = 374;
UPDATE "Unit" SET "evolvedName" = 'Macho Coin Cat' WHERE "unitNumber" = 375;
UPDATE "Unit" SET "evolvedName" = 'Rover Cat Mk II', "trueName" = 'Catellite' WHERE "unitNumber" = 376;
UPDATE "Unit" SET "evolvedName" = 'Kendo Cat', "trueName" = 'The Kitty of Liberty' WHERE "unitNumber" = 377;
UPDATE "Unit" SET "evolvedName" = 'Gothic Mitama' WHERE "unitNumber" = 378;
UPDATE "Unit" SET "evolvedName" = 'Ballet Cat', "trueName" = 'Curry Cat' WHERE "unitNumber" = 379;
UPDATE "Unit" SET "evolvedName" = 'Meow-sketeer' WHERE "unitNumber" = 380;
UPDATE "Unit" SET "evolvedName" = 'Harvest Cat' WHERE "unitNumber" = 381;
UPDATE "Unit" SET "evolvedName" = 'Macho Glass Cat', "trueName" = 'Macho Crystal Cat' WHERE "unitNumber" = 382;
UPDATE "Unit" SET "evolvedName" = 'Mystic Yulala', "trueName" = 'Spiritual Yulala' WHERE "unitNumber" = 383;
UPDATE "Unit" SET "evolvedName" = 'Satori Hikami & Cat CC' WHERE "unitNumber" = 384;
UPDATE "Unit" SET "evolvedName" = 'Akio Yabe CC', "trueName" = 'Akio & Gunder CC' WHERE "unitNumber" = 385;
UPDATE "Unit" SET "evolvedName" = 'Sairi Nijitani CC' WHERE "unitNumber" = 386;
UPDATE "Unit" SET "evolvedName" = 'Misaki Konno CC' WHERE "unitNumber" = 387;
UPDATE "Unit" SET "evolvedName" = 'Ren Katagiri CC' WHERE "unitNumber" = 388;
UPDATE "Unit" SET "evolvedName" = 'Karin Nekozuka CC' WHERE "unitNumber" = 389;
UPDATE "Unit" SET "evolvedName" = 'Aoi Hayakawa CC', "trueName" = 'Baseball Mask α' WHERE "unitNumber" = 390;
UPDATE "Unit" SET "evolvedName" = 'Mizuki Tachibana CC', "trueName" = 'Baseball Mask β' WHERE "unitNumber" = 391;
UPDATE "Unit" SET "evolvedName" = 'Hijiri Rokudo CC', "trueName" = 'Baseball Mask γ' WHERE "unitNumber" = 392;
UPDATE "Unit" SET "evolvedName" = 'Saki Nijima CC', "trueName" = 'Samba Saki CC' WHERE "unitNumber" = 393;
UPDATE "Unit" SET "evolvedName" = 'Subaru Hoshi CC', "trueName" = 'Dark Subaru CC' WHERE "unitNumber" = 394;
UPDATE "Unit" SET "evolvedName" = 'Miyabi Oyama CC', "trueName" = 'Baseball Mask δ' WHERE "unitNumber" = 395;
UPDATE "Unit" SET "evolvedName" = 'Ganglion the Ancient', "trueName" = 'Ganglion the Unleashed' WHERE "unitNumber" = 396;
UPDATE "Unit" SET "evolvedName" = 'Afterschool Sakura', "trueName" = 'Sacred Blade Sakura', "ultraName" = 'Sacred Blade Sakura Z' WHERE "unitNumber" = 397;
UPDATE "Unit" SET "evolvedName" = 'Mentori CC' WHERE "unitNumber" = 399;
UPDATE "Unit" SET "evolvedName" = 'Imoto CC' WHERE "unitNumber" = 400;
UPDATE "Unit" SET "evolvedName" = 'Volta', "trueName" = 'Gigavolta' WHERE "unitNumber" = 401;
UPDATE "Unit" SET "evolvedName" = 'Plug Suit Shinji', "trueName" = 'Plug Suit Shinji Black' WHERE "unitNumber" = 402;
UPDATE "Unit" SET "evolvedName" = 'Moon Gendo & Fuyutsuki Cats' WHERE "unitNumber" = 403;
UPDATE "Unit" SET "evolvedName" = 'Giraffe Unit-02' WHERE "unitNumber" = 404;
UPDATE "Unit" SET "evolvedName" = 'Plug Suit Kaworu', "trueName" = 'Moon Kaworu' WHERE "unitNumber" = 405;
UPDATE "Unit" SET "evolvedName" = 'Ayanami Cat (TBC)' WHERE "unitNumber" = 406;
UPDATE "Unit" SET "evolvedName" = 'Apron Asuka' WHERE "unitNumber" = 407;
UPDATE "Unit" SET "evolvedName" = 'Special Ops Mari' WHERE "unitNumber" = 408;
UPDATE "Unit" SET "evolvedName" = 'Plug Suit Rei', "trueName" = 'Reunion Li''l Rei' WHERE "unitNumber" = 409;
UPDATE "Unit" SET "evolvedName" = 'Plug Suit Asuka', "trueName" = 'Eyepatch Li''l Asuka' WHERE "unitNumber" = 410;
UPDATE "Unit" SET "evolvedName" = 'Plug Suit Mari' WHERE "unitNumber" = 411;
UPDATE "Unit" SET "evolvedName" = 'EVA Unit-00 & Cat' WHERE "unitNumber" = 412;
UPDATE "Unit" SET "evolvedName" = 'EVA Unit-01 & Cat', "trueName" = 'Determined Unit-01 & Cat' WHERE "unitNumber" = 413;
UPDATE "Unit" SET "evolvedName" = 'EVA Unit-02 & Cat', "trueName" = 'Unit-02, Code 777' WHERE "unitNumber" = 414;
UPDATE "Unit" SET "evolvedName" = 'Toji & Kensuke Cats' WHERE "unitNumber" = 415;
UPDATE "Unit" SET "evolvedName" = 'NERV Moon' WHERE "unitNumber" = 416;
UPDATE "Unit" SET "evolvedName" = 'Subterra Guardians', "trueName" = 'Subterra Sentinels' WHERE "unitNumber" = 417;
UPDATE "Unit" SET "evolvedName" = 'Corrupted Moneko' WHERE "unitNumber" = 418;
UPDATE "Unit" SET "evolvedName" = 'Pokota CC' WHERE "unitNumber" = 419;
UPDATE "Unit" SET "evolvedName" = 'Ovis CC' WHERE "unitNumber" = 420;
UPDATE "Unit" SET "evolvedName" = 'Coco CC' WHERE "unitNumber" = 421;
UPDATE "Unit" SET "evolvedName" = 'Mecha-Bun Mk II', "trueName" = 'Ultimate Mecha-Bun' WHERE "unitNumber" = 426;
UPDATE "Unit" SET "evolvedName" = 'Cat Guild Heroes', "trueName" = 'Cat Quest Heroes' WHERE "unitNumber" = 427;
UPDATE "Unit" SET "evolvedName" = 'Stylish Souma Cat' WHERE "unitNumber" = 428;
UPDATE "Unit" SET "evolvedName" = 'Hacker Geek Cat' WHERE "unitNumber" = 429;
UPDATE "Unit" SET "evolvedName" = 'Inspector Gabriel', "trueName" = 'Section Chief Gravicci', "ultraName" = 'Arcane Commissioner Gravicci' WHERE "unitNumber" = 431;
UPDATE "Unit" SET "evolvedName" = 'Black Betakkuma' WHERE "unitNumber" = 432;
UPDATE "Unit" SET "evolvedName" = 'Killer Nekokkuma' WHERE "unitNumber" = 433;
UPDATE "Unit" SET "evolvedName" = 'Wind Dancer Valkyrie' WHERE "unitNumber" = 435;
UPDATE "Unit" SET "evolvedName" = 'Nobilan Pasalan', "trueName" = 'Mystican Pasalan' WHERE "unitNumber" = 436;
UPDATE "Unit" SET "evolvedName" = 'Cat God the Awesome', "trueName" = 'Cat God the Golden' WHERE "unitNumber" = 437;
UPDATE "Unit" SET "evolvedName" = 'Waverider Kuu, type γ' WHERE "unitNumber" = 438;
UPDATE "Unit" SET "evolvedName" = 'Chronos the Infinite', "trueName" = 'Almighty Chronos' WHERE "unitNumber" = 439;
UPDATE "Unit" SET "evolvedName" = 'Nagisa & Cat', "trueName" = 'Law of Cycles Nagisa' WHERE "unitNumber" = 440;
UPDATE "Unit" SET "evolvedName" = 'Valiant D''arktanyan' WHERE "unitNumber" = 441;
UPDATE "Unit" SET "evolvedName" = 'Vendor Cat and Kitten', "trueName" = 'Tourist Cat' WHERE "unitNumber" = 442;
UPDATE "Unit" SET "evolvedName" = 'Power Driller Cat', "trueName" = 'Neo Driller Cat' WHERE "unitNumber" = 443;
UPDATE "Unit" SET "evolvedName" = 'Power Piledriver Cat', "trueName" = 'Neo Piledriver Cat' WHERE "unitNumber" = 444;
UPDATE "Unit" SET "evolvedName" = 'Power Cutter Cat', "trueName" = 'Neo Cutter Cat' WHERE "unitNumber" = 445;
UPDATE "Unit" SET "evolvedName" = 'Power Backhoe Cat', "trueName" = 'Neo Backhoe Cat' WHERE "unitNumber" = 446;
UPDATE "Unit" SET "evolvedName" = 'Power Saw Cat', "trueName" = 'Neo Saw Cat' WHERE "unitNumber" = 447;
UPDATE "Unit" SET "evolvedName" = 'Wargod Miyamoto', "trueName" = 'Immortal Miyamoto' WHERE "unitNumber" = 448;
UPDATE "Unit" SET "evolvedName" = 'Headmistress Jeanne ψ' WHERE "unitNumber" = 449;
UPDATE "Unit" SET "evolvedName" = 'Babel the Darkflame', "trueName" = 'God-Emperor Babel' WHERE "unitNumber" = 450;
UPDATE "Unit" SET "evolvedName" = 'Colossal Benkei' WHERE "unitNumber" = 451;
UPDATE "Unit" SET "evolvedName" = 'Modern Cat', "trueName" = 'Future Cat' WHERE "unitNumber" = 452;
UPDATE "Unit" SET "evolvedName" = 'Cutie MOMOCO' WHERE "unitNumber" = 455;
UPDATE "Unit" SET "evolvedName" = 'Sakura Matou CC', "trueName" = 'Dark Sakura CC' WHERE "unitNumber" = 456;
UPDATE "Unit" SET "evolvedName" = 'Novice Mage Shirou Cat' WHERE "unitNumber" = 457;
UPDATE "Unit" SET "evolvedName" = 'Heroic Spirit Archer Cat' WHERE "unitNumber" = 458;
UPDATE "Unit" SET "evolvedName" = 'Heroic Spirit Rider Cat' WHERE "unitNumber" = 459;
UPDATE "Unit" SET "evolvedName" = 'Gilgamesh & Kotomine Cats' WHERE "unitNumber" = 460;
UPDATE "Unit" SET "evolvedName" = 'Legelan Pasalan' WHERE "unitNumber" = 461;
UPDATE "Unit" SET "evolvedName" = 'Filibuster Cat Y', "trueName" = 'Metafilibuster' WHERE "unitNumber" = 462;
UPDATE "Unit" SET "evolvedName" = 'Doom Engine Pandora' WHERE "unitNumber" = 463;
UPDATE "Unit" SET "evolvedName" = 'Doguemon', "trueName" = 'Reborn Warrior Doguemon' WHERE "unitNumber" = 464;
UPDATE "Unit" SET "evolvedName" = 'Dark Lord Zeus' WHERE "unitNumber" = 466;
UPDATE "Unit" SET "evolvedName" = 'All-Powerful Super Zeus', "trueName" = 'Super S-Zeus' WHERE "unitNumber" = 467;
UPDATE "Unit" SET "evolvedName" = 'Holy Warrior Phoenix', "trueName" = 'Head Rococo' WHERE "unitNumber" = 468;
UPDATE "Unit" SET "evolvedName" = 'Imposter Super Devil', "trueName" = 'Super D-Devil' WHERE "unitNumber" = 469;
UPDATE "Unit" SET "evolvedName" = 'Wondermaria' WHERE "unitNumber" = 470;
UPDATE "Unit" SET "evolvedName" = 'Perfect Heracrist' WHERE "unitNumber" = 471;
UPDATE "Unit" SET "evolvedName" = 'Beastly Nero' WHERE "unitNumber" = 472;
UPDATE "Unit" SET "evolvedName" = 'Holy Yamato', "trueName" = 'Rampaging Yamato' WHERE "unitNumber" = 473;
UPDATE "Unit" SET "evolvedName" = 'Cross Angel', "trueName" = 'Strike Angel' WHERE "unitNumber" = 474;
UPDATE "Unit" SET "evolvedName" = 'Warrior King Cat' WHERE "unitNumber" = 475;
UPDATE "Unit" SET "evolvedName" = 'Infernal Cat' WHERE "unitNumber" = 476;
UPDATE "Unit" SET "evolvedName" = 'Old Guardian Cat' WHERE "unitNumber" = 477;
UPDATE "Unit" SET "evolvedName" = 'Luminalia' WHERE "unitNumber" = 478;
UPDATE "Unit" SET "evolvedName" = 'Professor Abyss' WHERE "unitNumber" = 481;
UPDATE "Unit" SET "evolvedName" = 'Souma ＆ Cat', "trueName" = 'Cat-Eared Souma' WHERE "unitNumber" = 482;
UPDATE "Unit" SET "evolvedName" = 'Kano ＆ Souma ＆ Cat' WHERE "unitNumber" = 483;
UPDATE "Unit" SET "evolvedName" = 'Dark Rider Valkyrie' WHERE "unitNumber" = 484;
UPDATE "Unit" SET "evolvedName" = 'Calette CC' WHERE "unitNumber" = 485;
UPDATE "Unit" SET "evolvedName" = 'Swordswoman Hina' WHERE "unitNumber" = 486;
UPDATE "Unit" SET "evolvedName" = 'EVA Unit-08 & Cat' WHERE "unitNumber" = 487;
UPDATE "Unit" SET "evolvedName" = 'NNN Wunder', "trueName" = 'Vanished NNN Wunder' WHERE "unitNumber" = 488;
UPDATE "Unit" SET "evolvedName" = 'Captain Misato' WHERE "unitNumber" = 489;
UPDATE "Unit" SET "evolvedName" = 'First Officer Ritsuko' WHERE "unitNumber" = 490;
UPDATE "Unit" SET "evolvedName" = 'Awakened Ayanami' WHERE "unitNumber" = 491;
UPDATE "Unit" SET "evolvedName" = 'Gaia the Supreme' WHERE "unitNumber" = 493;
UPDATE "Unit" SET "evolvedName" = 'Seabreeze Coppermine, type κ' WHERE "unitNumber" = 494;
UPDATE "Unit" SET "evolvedName" = 'Flamenco Cat', "trueName" = 'Bellydance Cat' WHERE "unitNumber" = 495;
UPDATE "Unit" SET "evolvedName" = 'Wargod Kaihime', "trueName" = 'Immortal Kaihime' WHERE "unitNumber" = 496;
UPDATE "Unit" SET "evolvedName" = 'Shakurel Macho Cat' WHERE "unitNumber" = 497;
UPDATE "Unit" SET "evolvedName" = 'Shakurel Lion CC' WHERE "unitNumber" = 498;
UPDATE "Unit" SET "evolvedName" = 'Shakurel Tiger CC' WHERE "unitNumber" = 499;
UPDATE "Unit" SET "evolvedName" = 'Shakurel Panda CC' WHERE "unitNumber" = 500;
UPDATE "Unit" SET "evolvedName" = 'Baka Cat Bros' WHERE "unitNumber" = 501;
UPDATE "Unit" SET "evolvedName" = 'Myrcia, type ξ', "trueName" = 'Divine Myrcia' WHERE "unitNumber" = 502;
UPDATE "Unit" SET "evolvedName" = 'Gladios the Annihilator', "trueName" = 'God-Emperor Gladios' WHERE "unitNumber" = 505;
UPDATE "Unit" SET "evolvedName" = 'Eyewaltz CC', "trueName" = 'Nameless Eyewaltz CC' WHERE "unitNumber" = 506;
UPDATE "Unit" SET "evolvedName" = 'Supercat' WHERE "unitNumber" = 507;
UPDATE "Unit" SET "evolvedName" = 'Ryu Cat CC' WHERE "unitNumber" = 508;
UPDATE "Unit" SET "evolvedName" = 'Chun-Li Cat CC' WHERE "unitNumber" = 509;
UPDATE "Unit" SET "evolvedName" = 'Akuma CC' WHERE "unitNumber" = 510;
UPDATE "Unit" SET "evolvedName" = 'Ryu CC', "trueName" = 'Kage' WHERE "unitNumber" = 511;
UPDATE "Unit" SET "evolvedName" = 'Chun-Li CC' WHERE "unitNumber" = 512;
UPDATE "Unit" SET "evolvedName" = 'Guile CC' WHERE "unitNumber" = 513;
UPDATE "Unit" SET "evolvedName" = 'Zangief CC' WHERE "unitNumber" = 514;
UPDATE "Unit" SET "evolvedName" = 'Blanka CC' WHERE "unitNumber" = 515;
UPDATE "Unit" SET "evolvedName" = 'Dhalsim CC' WHERE "unitNumber" = 516;
UPDATE "Unit" SET "evolvedName" = 'Ken CC', "trueName" = 'Crimson King of Battle Ken' WHERE "unitNumber" = 517;
UPDATE "Unit" SET "evolvedName" = 'Akuma Lion' WHERE "unitNumber" = 518;
UPDATE "Unit" SET "evolvedName" = 'Ultimate Lasvoss', "trueName" = 'Lasvoss Reborn' WHERE "unitNumber" = 519;
UPDATE "Unit" SET "evolvedName" = 'Bad-Luck Ebisu' WHERE "unitNumber" = 520;
UPDATE "Unit" SET "evolvedName" = 'Twintail Medusa Cat', "trueName" = 'Naga Cat' WHERE "unitNumber" = 521;
UPDATE "Unit" SET "evolvedName" = 'Medalist Cat', "trueName" = 'Fiend Cat' WHERE "unitNumber" = 522;
UPDATE "Unit" SET "evolvedName" = 'Sifu Cat', "trueName" = 'Shigong Cat' WHERE "unitNumber" = 523;
UPDATE "Unit" SET "evolvedName" = 'Kinrangers RoboForce', "trueName" = 'Kinrangers GigaForce' WHERE "unitNumber" = 525;
UPDATE "Unit" SET "evolvedName" = 'Snow Angel Twinstars, type Φ' WHERE "unitNumber" = 526;
UPDATE "Unit" SET "evolvedName" = 'Jellycat', "trueName" = 'Jelly Dumpling Cat' WHERE "unitNumber" = 527;
UPDATE "Unit" SET "evolvedName" = 'Vodka Cat', "trueName" = 'Royal Guard Cat' WHERE "unitNumber" = 528;
UPDATE "Unit" SET "evolvedName" = 'Ritual Saint Kasli' WHERE "unitNumber" = 529;
UPDATE "Unit" SET "evolvedName" = 'Herme CC' WHERE "unitNumber" = 530;
UPDATE "Unit" SET "evolvedName" = 'Assassin BearCat', "trueName" = 'Cadaver BearCat' WHERE "unitNumber" = 531;
UPDATE "Unit" SET "evolvedName" = 'Urs & Minka', "trueName" = 'Awakened Urs' WHERE "unitNumber" = 532;
UPDATE "Unit" SET "evolvedName" = 'Nighthunter Saki', "trueName" = 'Bad Blaster Saki' WHERE "unitNumber" = 533;
UPDATE "Unit" SET "evolvedName" = 'Hades the Deathdealer', "trueName" = 'Almighty Hades' WHERE "unitNumber" = 534;
UPDATE "Unit" SET "evolvedName" = 'Hatsune Miku CC' WHERE "unitNumber" = 535;
UPDATE "Unit" SET "evolvedName" = 'Sakura Miku CC' WHERE "unitNumber" = 536;
UPDATE "Unit" SET "evolvedName" = 'Kagamine Rin & Len CC' WHERE "unitNumber" = 537;
UPDATE "Unit" SET "evolvedName" = 'Miku Cat CC' WHERE "unitNumber" = 538;
UPDATE "Unit" SET "evolvedName" = 'Quarterback Cat', "trueName" = 'Gridiron Cat' WHERE "unitNumber" = 539;
UPDATE "Unit" SET "evolvedName" = 'Kasli, Daughter of Chaos' WHERE "unitNumber" = 543;
UPDATE "Unit" SET "evolvedName" = 'True Kyosaka Nanaho' WHERE "unitNumber" = 544;
UPDATE "Unit" SET "evolvedName" = 'Miasma Cat', "trueName" = 'Bubble Cat' WHERE "unitNumber" = 545;
UPDATE "Unit" SET "evolvedName" = 'Papalan Pasalan', "trueName" = 'Sukelan Kakulan' WHERE "unitNumber" = 546;
UPDATE "Unit" SET "evolvedName" = 'Heavenly Herald Rei' WHERE "unitNumber" = 547;
UPDATE "Unit" SET "evolvedName" = '4th Angel Cat' WHERE "unitNumber" = 548;
UPDATE "Unit" SET "evolvedName" = '6th Angel Cat' WHERE "unitNumber" = 549;
UPDATE "Unit" SET "evolvedName" = '10th Angel Cat' WHERE "unitNumber" = 550;
UPDATE "Unit" SET "evolvedName" = '9th Angel Cat' WHERE "unitNumber" = 551;
UPDATE "Unit" SET "evolvedName" = 'Moon Kaworu Cat' WHERE "unitNumber" = 552;
UPDATE "Unit" SET "evolvedName" = 'Boomerang Cat', "trueName" = 'Fried Chicken Cat' WHERE "unitNumber" = 553;
UPDATE "Unit" SET "evolvedName" = 'Mystic Uril', "trueName" = 'Esoteric Uril' WHERE "unitNumber" = 554;
UPDATE "Unit" SET "evolvedName" = 'All-Loving Shaman Khan' WHERE "unitNumber" = 555;
UPDATE "Unit" SET "evolvedName" = 'Holy King Alibaba', "trueName" = 'Ghost Alibaba' WHERE "unitNumber" = 556;
UPDATE "Unit" SET "evolvedName" = 'Heavenly Lord Jack' WHERE "unitNumber" = 557;
UPDATE "Unit" SET "evolvedName" = 'Lucky Gacha Cat' WHERE "unitNumber" = 558;
UPDATE "Unit" SET "evolvedName" = 'Hell Sentinel Emma', "trueName" = 'Hell Commissioner Emma' WHERE "unitNumber" = 559;
UPDATE "Unit" SET "evolvedName" = 'Megurine Luka CC' WHERE "unitNumber" = 560;
UPDATE "Unit" SET "evolvedName" = 'MEIKO & Cat CC' WHERE "unitNumber" = 561;
UPDATE "Unit" SET "evolvedName" = 'Luka Cat CC' WHERE "unitNumber" = 562;
UPDATE "Unit" SET "evolvedName" = 'Aquabuster Saki', "trueName" = 'Aquablaster Saki' WHERE "unitNumber" = 563;
UPDATE "Unit" SET "evolvedName" = 'Bikinilan Pasalan', "trueName" = 'Fabulous Pasalan' WHERE "unitNumber" = 564;
UPDATE "Unit" SET "evolvedName" = 'Macho Suntan Cat', "trueName" = 'Permed Suntan Cat' WHERE "unitNumber" = 565;
UPDATE "Unit" SET "evolvedName" = 'Sweet Bro Cats', "trueName" = 'Gelato Bro Cats' WHERE "unitNumber" = 566;
UPDATE "Unit" SET "evolvedName" = 'Idi:N2', "trueName" = 'Idi:NX' WHERE "unitNumber" = 568;
UPDATE "Unit" SET "evolvedName" = 'Gravolo', "trueName" = 'Gravolodon' WHERE "unitNumber" = 569;
UPDATE "Unit" SET "evolvedName" = 'Nightmare King Vars', "trueName" = 'Halloween Knight Vars' WHERE "unitNumber" = 570;
UPDATE "Unit" SET "evolvedName" = 'E. Honda CC' WHERE "unitNumber" = 571;
UPDATE "Unit" SET "evolvedName" = 'Balrog CC' WHERE "unitNumber" = 572;
UPDATE "Unit" SET "evolvedName" = 'Vega CC' WHERE "unitNumber" = 573;
UPDATE "Unit" SET "evolvedName" = 'Sagat CC' WHERE "unitNumber" = 574;
UPDATE "Unit" SET "evolvedName" = 'M. Bison CC' WHERE "unitNumber" = 575;
UPDATE "Unit" SET "evolvedName" = 'C. Honda CC' WHERE "unitNumber" = 576;
UPDATE "Unit" SET "evolvedName" = 'Balrog Cat CC' WHERE "unitNumber" = 577;
UPDATE "Unit" SET "evolvedName" = 'Vega Cat CC' WHERE "unitNumber" = 578;
UPDATE "Unit" SET "evolvedName" = 'Sagat Cat CC' WHERE "unitNumber" = 579;
UPDATE "Unit" SET "evolvedName" = 'M. Bison Cat CC' WHERE "unitNumber" = 580;
UPDATE "Unit" SET "evolvedName" = 'Boulder Cat' WHERE "unitNumber" = 581;
UPDATE "Unit" SET "evolvedName" = 'Hatsune Miku CC: MM2020 Osaka' WHERE "unitNumber" = 582;
UPDATE "Unit" SET "evolvedName" = 'Hatsune Miku CC: MM2020 Tokyo' WHERE "unitNumber" = 583;
UPDATE "Unit" SET "evolvedName" = 'Maeda Christmas', "trueName" = 'Maeda Christmas DX' WHERE "unitNumber" = 584;
UPDATE "Unit" SET "evolvedName" = 'Mighty Aegis Garu' WHERE "unitNumber" = 585;
UPDATE "Unit" SET "evolvedName" = 'Tyrant Cat' WHERE "unitNumber" = 586;
UPDATE "Unit" SET "evolvedName" = 'Chocoladite' WHERE "unitNumber" = 587;
UPDATE "Unit" SET "evolvedName" = 'First-Love Myrcia ξ' WHERE "unitNumber" = 588;
UPDATE "Unit" SET "evolvedName" = 'Sweetheart Neneko', "trueName" = 'True Love Neneko' WHERE "unitNumber" = 589;
UPDATE "Unit" SET "evolvedName" = 'Snow Miku CC 2021' WHERE "unitNumber" = 590;
UPDATE "Unit" SET "evolvedName" = 'KAITO & Cat CC' WHERE "unitNumber" = 591;
UPDATE "Unit" SET "evolvedName" = 'Neko Rin CC' WHERE "unitNumber" = 592;
UPDATE "Unit" SET "evolvedName" = 'Neko Len CC' WHERE "unitNumber" = 593;
UPDATE "Unit" SET "evolvedName" = 'Atlantis Logistix', "trueName" = 'Ultra Atlantis Logistix' WHERE "unitNumber" = 594;
UPDATE "Unit" SET "evolvedName" = 'Everbloom Kamukura', "trueName" = 'Everbloom Lord Kamukura' WHERE "unitNumber" = 595;
UPDATE "Unit" SET "evolvedName" = 'Ranma Saotome (F)' WHERE "unitNumber" = 596;
UPDATE "Unit" SET "evolvedName" = 'Akane Tendo (Gi)' WHERE "unitNumber" = 597;
UPDATE "Unit" SET "evolvedName" = 'Ryoga Hibiki' WHERE "unitNumber" = 598;
UPDATE "Unit" SET "evolvedName" = 'Shampoo' WHERE "unitNumber" = 599;
UPDATE "Unit" SET "evolvedName" = 'Mousse' WHERE "unitNumber" = 600;
UPDATE "Unit" SET "evolvedName" = 'Happosai (Lewd)' WHERE "unitNumber" = 601;
UPDATE "Unit" SET "evolvedName" = 'Ukyo Kuonji' WHERE "unitNumber" = 602;
UPDATE "Unit" SET "evolvedName" = 'Tatewaki Kuno' WHERE "unitNumber" = 603;
UPDATE "Unit" SET "evolvedName" = 'Ranma Cat (F)' WHERE "unitNumber" = 604;
UPDATE "Unit" SET "evolvedName" = 'Akane Cat (Gi)' WHERE "unitNumber" = 605;
UPDATE "Unit" SET "evolvedName" = 'Genma Cat' WHERE "unitNumber" = 606;
UPDATE "Unit" SET "evolvedName" = 'Swashbuckler Kanna', "trueName" = 'Fabled Adventure Girl Kanna' WHERE "unitNumber" = 607;
UPDATE "Unit" SET "evolvedName" = 'Dark Beastlord Garu' WHERE "unitNumber" = 609;
UPDATE "Unit" SET "evolvedName" = 'King Ingot Cat', "trueName" = 'King Nekokhamen' WHERE "unitNumber" = 610;
UPDATE "Unit" SET "evolvedName" = 'Shin Godzilla Cat' WHERE "unitNumber" = 611;
UPDATE "Unit" SET "evolvedName" = 'Empress Cat' WHERE "unitNumber" = 612;
UPDATE "Unit" SET "evolvedName" = 'Cat Mask Doron', "trueName" = 'Awakened Doron' WHERE "unitNumber" = 613;
UPDATE "Unit" SET "evolvedName" = 'The Southern Sun', "trueName" = 'The Southern Sunflare' WHERE "unitNumber" = 614;
UPDATE "Unit" SET "evolvedName" = 'Golden Kabuto Cat' WHERE "unitNumber" = 615;
UPDATE "Unit" SET "evolvedName" = 'King Kuwagata Cat' WHERE "unitNumber" = 616;
UPDATE "Unit" SET "evolvedName" = 'Dark Summoner Satoru', "trueName" = 'Devil Hunter Satoru' WHERE "unitNumber" = 617;
UPDATE "Unit" SET "evolvedName" = 'Wargod Amakusa', "trueName" = 'Immortal Amakusa' WHERE "unitNumber" = 618;
UPDATE "Unit" SET "evolvedName" = 'Lilin π', "trueName" = 'Divine Lilin π' WHERE "unitNumber" = 619;
UPDATE "Unit" SET "evolvedName" = 'Wicked King Hevijak', "trueName" = 'God-Emperor Hevijak' WHERE "unitNumber" = 620;
UPDATE "Unit" SET "evolvedName" = 'Evil Aku Researcher', "trueName" = 'Cat Researcher' WHERE "unitNumber" = 621;
UPDATE "Unit" SET "evolvedName" = 'Lord of Ruin Jagando Jr.' WHERE "unitNumber" = 622;
UPDATE "Unit" SET "evolvedName" = 'Komuso Cat', "trueName" = 'Brass Cat' WHERE "unitNumber" = 623;
UPDATE "Unit" SET "evolvedName" = 'Dodgeball Kunio-kun' WHERE "unitNumber" = 624;
UPDATE "Unit" SET "evolvedName" = 'Furilan Pasalan', "trueName" = 'Ragelan Pasalan' WHERE "unitNumber" = 625;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Macho Cat', "trueName" = 'Brainwashed Mohawk Cat' WHERE "unitNumber" = 629;
UPDATE "Unit" SET "evolvedName" = 'Tea Master Cat' WHERE "unitNumber" = 630;
UPDATE "Unit" SET "evolvedName" = 'Yaminoir', "trueName" = 'Yaminora' WHERE "unitNumber" = 631;
UPDATE "Unit" SET "evolvedName" = 'Siege Walker Diabolosa', "trueName" = 'Obliterator Diabolosa' WHERE "unitNumber" = 632;
UPDATE "Unit" SET "evolvedName" = 'Chunchun Haunters', "trueName" = 'Grand Chunchun Haunters' WHERE "unitNumber" = 633;
UPDATE "Unit" SET "evolvedName" = 'Black Knight Kyklops', "trueName" = 'Demon Knight Kyklops' WHERE "unitNumber" = 634;
UPDATE "Unit" SET "evolvedName" = 'Hundred-Million-Dollar Cat' WHERE "unitNumber" = 635;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Wall Cat', "trueName" = 'Brainwashed Eraser Cat' WHERE "unitNumber" = 636;
UPDATE "Unit" SET "evolvedName" = 'Iz the Alluring Dancer' WHERE "unitNumber" = 641;
UPDATE "Unit" SET "evolvedName" = 'Grand Lucifer', "trueName" = 'Almighty Lucifer' WHERE "unitNumber" = 642;
UPDATE "Unit" SET "evolvedName" = 'Superfeline II', "trueName" = 'True Superfeline' WHERE "unitNumber" = 643;
UPDATE "Unit" SET "evolvedName" = 'Bittersweet Mekako', "trueName" = 'Minty Love Mekako' WHERE "unitNumber" = 644;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Brave Cat', "trueName" = 'Brainwashed Dark Cat' WHERE "unitNumber" = 645;
UPDATE "Unit" SET "evolvedName" = 'Macho Firecracker Cat' WHERE "unitNumber" = 646;
UPDATE "Unit" SET "evolvedName" = 'Huntress Terun ζ', "trueName" = 'Divine Huntress Terun ζ' WHERE "unitNumber" = 647;
UPDATE "Unit" SET "evolvedName" = 'Lovestruck Greater Demon' WHERE "unitNumber" = 648;
UPDATE "Unit" SET "evolvedName" = 'Wargod Hanzo', "trueName" = 'Immortal Hanzo' WHERE "unitNumber" = 649;
UPDATE "Unit" SET "evolvedName" = 'Girlfriend Cat' WHERE "unitNumber" = 650;
UPDATE "Unit" SET "evolvedName" = 'Iron-Masked Lion Cat' WHERE "unitNumber" = 651;
UPDATE "Unit" SET "evolvedName" = 'Chalkboard Punk Cat' WHERE "unitNumber" = 652;
UPDATE "Unit" SET "evolvedName" = 'Storm Beast Naala', "trueName" = 'Awakened Naala' WHERE "unitNumber" = 653;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Sexy Legs Cat', "trueName" = 'Brainwashed Macho Legs Cat' WHERE "unitNumber" = 654;
UPDATE "Unit" SET "evolvedName" = 'Blizana', "trueName" = 'Blizarena' WHERE "unitNumber" = 655;
UPDATE "Unit" SET "evolvedName" = 'Mystic Egg: N001', "trueName" = 'Haniwa Cat' WHERE "unitNumber" = 656;
UPDATE "Unit" SET "evolvedName" = 'Iz the Lady of Mourning' WHERE "unitNumber" = 657;
UPDATE "Unit" SET "evolvedName" = 'Cinnabar Egg: N101', "trueName" = 'Courier Cat' WHERE "unitNumber" = 658;
UPDATE "Unit" SET "evolvedName" = 'Teal Egg: N102', "trueName" = 'Catarzan' WHERE "unitNumber" = 659;
UPDATE "Unit" SET "evolvedName" = 'Sea King Daliasan', "trueName" = 'God-Emperor Daliasan' WHERE "unitNumber" = 660;
UPDATE "Unit" SET "evolvedName" = 'Wedding Chronos' WHERE "unitNumber" = 661;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Giraffe Cat', "trueName" = 'Brainwashed Lion Cat' WHERE "unitNumber" = 662;
UPDATE "Unit" SET "evolvedName" = 'Black Egg: N103', "trueName" = 'Gas Mask Cat' WHERE "unitNumber" = 663;
UPDATE "Unit" SET "evolvedName" = 'Green Egg: N104', "trueName" = 'Surgeon Cat' WHERE "unitNumber" = 664;
UPDATE "Unit" SET "evolvedName" = 'Dark Egg: N201', "trueName" = 'Exorcist Cat' WHERE "unitNumber" = 665;
UPDATE "Unit" SET "evolvedName" = 'Night Beach Lilinπ' WHERE "unitNumber" = 666;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed UFO Cat', "trueName" = 'Brainwashed Flying Cat' WHERE "unitNumber" = 667;
UPDATE "Unit" SET "evolvedName" = 'Grand Yokai Tengu', "trueName" = 'Immortal Master Tengu' WHERE "unitNumber" = 668;
UPDATE "Unit" SET "evolvedName" = 'Evil Egg: N003', "trueName" = 'Cat Cactus' WHERE "unitNumber" = 669;
UPDATE "Unit" SET "evolvedName" = 'Cinnabar Egg: N202', "trueName" = 'Armored Firefly Cat' WHERE "unitNumber" = 670;
UPDATE "Unit" SET "evolvedName" = 'Ranma Saotome (Cheer)' WHERE "unitNumber" = 671;
UPDATE "Unit" SET "evolvedName" = 'Genma Saotome' WHERE "unitNumber" = 672;
UPDATE "Unit" SET "evolvedName" = 'Extraterrestrial Envanz', "trueName" = 'Extradimensional Envanz' WHERE "unitNumber" = 674;
UPDATE "Unit" SET "evolvedName" = 'Teal Egg: N105', "trueName" = 'Racquet Cat' WHERE "unitNumber" = 675;
UPDATE "Unit" SET "evolvedName" = 'Amber Egg: N106', "trueName" = 'Mushroom Cat' WHERE "unitNumber" = 676;
UPDATE "Unit" SET "evolvedName" = 'Osamu Mikumo & Cat CC' WHERE "unitNumber" = 677;
UPDATE "Unit" SET "evolvedName" = 'Yuma Kuga & Cat CC' WHERE "unitNumber" = 678;
UPDATE "Unit" SET "evolvedName" = 'Chika Amatori & Cat CC' WHERE "unitNumber" = 679;
UPDATE "Unit" SET "evolvedName" = 'Sakura CC' WHERE "unitNumber" = 680;
UPDATE "Unit" SET "evolvedName" = 'Luke CC' WHERE "unitNumber" = 681;
UPDATE "Unit" SET "evolvedName" = 'Illusory Guardian Vega', "trueName" = 'Lady of Deception Vega' WHERE "unitNumber" = 682;
UPDATE "Unit" SET "evolvedName" = 'Nosferatu Yukimura', "trueName" = 'Vampiric Yukimura' WHERE "unitNumber" = 683;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Whale Cat', "trueName" = 'Brainwashed Island Cat' WHERE "unitNumber" = 684;
UPDATE "Unit" SET "evolvedName" = 'Mystic Egg: N004', "trueName" = 'Supercar Cat' WHERE "unitNumber" = 685;
UPDATE "Unit" SET "evolvedName" = 'Goddess of Sunrise Sirius' WHERE "unitNumber" = 686;
UPDATE "Unit" SET "evolvedName" = 'Reindeer Terunζ' WHERE "unitNumber" = 687;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Dragon Cat', "trueName" = 'Brainwashed King Dragon Cat' WHERE "unitNumber" = 688;
UPDATE "Unit" SET "evolvedName" = 'Paragon Cat' WHERE "unitNumber" = 689;
UPDATE "Unit" SET "evolvedName" = 'King of Destiny Phonoa' WHERE "unitNumber" = 690;
UPDATE "Unit" SET "evolvedName" = 'Elder Egg: N000', "trueName" = 'Ape Lord Luza' WHERE "unitNumber" = 691;
UPDATE "Unit" SET "evolvedName" = 'Oni Landshaker Kozuchimaru', "trueName" = 'Oni Battlepod Kozuchimaru' WHERE "unitNumber" = 692;
UPDATE "Unit" SET "evolvedName" = 'Black Butler Vigler' WHERE "unitNumber" = 693;
UPDATE "Unit" SET "evolvedName" = 'Brainwashed Mythic Titan', "trueName" = 'Brainwashed Jamiera Cat' WHERE "unitNumber" = 694;
UPDATE "Unit" SET "evolvedName" = 'True Killer Tank Cat' WHERE "unitNumber" = 695;
UPDATE "Unit" SET "evolvedName" = 'Stealth Class Rep Cat' WHERE "unitNumber" = 696;
UPDATE "Unit" SET "evolvedName" = 'Violet Egg: N107', "trueName" = 'Cat Chief' WHERE "unitNumber" = 697;
UPDATE "Unit" SET "evolvedName" = 'Bloody Jack', "trueName" = 'Lightning Jack' WHERE "unitNumber" = 698;
UPDATE "Unit" SET "evolvedName" = 'Rabbit Champion Satoru' WHERE "unitNumber" = 699;
UPDATE "Unit" SET "evolvedName" = 'Mystic Egg: N005', "trueName" = 'Hitman Cat' WHERE "unitNumber" = 700;
UPDATE "Unit" SET "evolvedName" = 'King of Extinction Phono' WHERE "unitNumber" = 705;
UPDATE "Unit" SET "evolvedName" = 'Teal Egg: N108', "trueName" = 'Soap Cat' WHERE "unitNumber" = 706;
UPDATE "Unit" SET "evolvedName" = 'Dark Egg: N109', "trueName" = 'Barrel Cat' WHERE "unitNumber" = 707;
UPDATE "Unit" SET "evolvedName" = 'Kinjirou Cat' WHERE "unitNumber" = 708;
UPDATE "Unit" SET "evolvedName" = 'Blue-Eyed Asuka' WHERE "unitNumber" = 709;
UPDATE "Unit" SET "evolvedName" = 'EVA Unit-13 & Cat' WHERE "unitNumber" = 710;
UPDATE "Unit" SET "evolvedName" = 'Betrothed Pasalan' WHERE "unitNumber" = 711;
UPDATE "Unit" SET "evolvedName" = 'Kaolan Pasalan', "trueName" = 'Kaolan Tatalan' WHERE "unitNumber" = 712;
UPDATE "Unit" SET "evolvedName" = 'Violet Egg: N203', "trueName" = 'Clown Cat' WHERE "unitNumber" = 713;
UPDATE "Unit" SET "evolvedName" = 'Deep-Diver Kanna', "trueName" = 'Great Deep-Diver Kanna' WHERE "unitNumber" = 714;
UPDATE "Unit" SET "evolvedName" = 'Attack Battalion Convoys', "trueName" = 'Hyper Battalion Convoys' WHERE "unitNumber" = 715;
UPDATE "Unit" SET "evolvedName" = 'Mystic Egg: N111', "trueName" = 'Cop Cat' WHERE "unitNumber" = 716;
UPDATE "Unit" SET "evolvedName" = 'Amber Egg: N110', "trueName" = 'Farmboy Cat' WHERE "unitNumber" = 717;
UPDATE "Unit" SET "evolvedName" = 'Cone Cat' WHERE "unitNumber" = 718;
UPDATE "Unit" SET "evolvedName" = 'Tetsukachi' WHERE "unitNumber" = 719;
UPDATE "Unit" SET "evolvedName" = 'Devil Egg: N006', "trueName" = 'Fallen Bear Cat' WHERE "unitNumber" = 720;
UPDATE "Unit" SET "evolvedName" = 'Dodgeball Riki' WHERE "unitNumber" = 721;
UPDATE "Unit" SET "evolvedName" = 'Hatsune Miku XVI CC' WHERE "unitNumber" = 722;
UPDATE "Unit" SET "evolvedName" = 'Nefer Aset', "trueName" = 'Almighty Aset' WHERE "unitNumber" = 723;
UPDATE "Unit" SET "evolvedName" = 'Mystic Egg: N112', "trueName" = 'Cat Egg Pod' WHERE "unitNumber" = 724;
UPDATE "Unit" SET "evolvedName" = 'Gourmand Ninja Girl Tomoe' WHERE "unitNumber" = 725;
UPDATE "Unit" SET "evolvedName" = 'Medal Emperor' WHERE "unitNumber" = 726;
UPDATE "Unit" SET "evolvedName" = 'SOL DAE ROKKER CC' WHERE "unitNumber" = 727;
UPDATE "Unit" SET "evolvedName" = 'Master of Mind Catcrates' WHERE "unitNumber" = 728;
UPDATE "Unit" SET "evolvedName" = 'Cinnabar Egg: N204', "trueName" = 'Lion Dancer Cat' WHERE "unitNumber" = 730;
UPDATE "Unit" SET "evolvedName" = 'Dawnbringer Izanagi' WHERE "unitNumber" = 731;
UPDATE "Unit" SET "evolvedName" = 'Pegasa ν', "trueName" = 'Uninterested in the plots and schemes of adults,' WHERE "unitNumber" = 733;
UPDATE "Unit" SET "evolvedName" = 'Midlife Crisis Cat' WHERE "unitNumber" = 735;
UPDATE "Unit" SET "evolvedName" = 'Arctic Bloom Cat' WHERE "unitNumber" = 736;
UPDATE "Unit" SET "evolvedName" = 'Floral Kalisa, type X' WHERE "unitNumber" = 737;
UPDATE "Unit" SET "evolvedName" = 'Izanami of Eventide' WHERE "unitNumber" = 738;
UPDATE "Unit" SET "evolvedName" = 'Mimic Cat' WHERE "unitNumber" = 740;
UPDATE "Unit" SET "evolvedName" = 'Daji & Cat' WHERE "unitNumber" = 741;
UPDATE "Unit" SET "evolvedName" = 'Mesmerizing Tune - Mollyanna' WHERE "unitNumber" = 742;
UPDATE "Unit" SET "evolvedName" = 'Madhead Cat' WHERE "unitNumber" = 743;
UPDATE "Unit" SET "evolvedName" = 'Mercenary Leader Felix Cat' WHERE "unitNumber" = 744;
UPDATE "Unit" SET "evolvedName" = 'Birthday Dotty Cat' WHERE "unitNumber" = 745;
UPDATE "Unit" SET "evolvedName" = 'Kenshin Himura CC' WHERE "unitNumber" = 746;
UPDATE "Unit" SET "evolvedName" = 'Sanosuke Sagara CC' WHERE "unitNumber" = 747;
UPDATE "Unit" SET "evolvedName" = 'Aoshi Shinomori CC' WHERE "unitNumber" = 748;
UPDATE "Unit" SET "evolvedName" = 'Hajime Saito CC' WHERE "unitNumber" = 749;
UPDATE "Unit" SET "evolvedName" = 'Li''l Kaoru CC' WHERE "unitNumber" = 750;
UPDATE "Unit" SET "evolvedName" = 'Li''l Yahiko CC' WHERE "unitNumber" = 751;
UPDATE "Unit" SET "evolvedName" = 'Battosai Cat' WHERE "unitNumber" = 752;
UPDATE "Unit" SET "evolvedName" = 'Swordscat Kaoru' WHERE "unitNumber" = 753;
UPDATE "Unit" SET "evolvedName" = 'Wargod Mitsuhide' WHERE "unitNumber" = 754;
UPDATE "Unit" SET "evolvedName" = 'Wedding Cake Machine' WHERE "unitNumber" = 756;
UPDATE "Unit" SET "evolvedName" = 'Violet Egg: N205', "trueName" = 'Bride Cat' WHERE "unitNumber" = 757;
UPDATE "Unit" SET "evolvedName" = 'Trixi the Revenant' WHERE "unitNumber" = 758;
UPDATE "Unit" SET "evolvedName" = 'Music Fest Thundia β' WHERE "unitNumber" = 759;
UPDATE "Unit" SET "evolvedName" = 'Ballistic Dragon Gunduros' WHERE "unitNumber" = 760;
UPDATE "Unit" SET "evolvedName" = 'Mecha Dynasaurus Cat' WHERE "unitNumber" = 763;
UPDATE "Unit" SET "evolvedName" = 'Cinnabar Egg: N206', "trueName" = 'Clam Cat' WHERE "unitNumber" = 765;
UPDATE "Unit" SET "evolvedName" = 'Sardine CC', "trueName" = 'Dropping in from "Survive! Mola Mola!" Tiny bones' WHERE "unitNumber" = 766;
UPDATE "Unit" SET "evolvedName" = 'Squid CC' WHERE "unitNumber" = 767;
UPDATE "Unit" SET "evolvedName" = 'Taitenki CC' WHERE "unitNumber" = 768;
UPDATE "Unit" SET "evolvedName" = 'Ravenous Cherry' WHERE "unitNumber" = 769;
UPDATE "Unit" SET "evolvedName" = 'Master of Life Catnova' WHERE "unitNumber" = 771;
UPDATE "Unit" SET "evolvedName" = 'Sodom-o''-Lantern' WHERE "unitNumber" = 772;
UPDATE "Unit" SET "evolvedName" = 'Mama Mummy Sumo' WHERE "unitNumber" = 773;
UPDATE "Unit" SET "evolvedName" = 'Steel Sergeant Axel' WHERE "unitNumber" = 774;
UPDATE "Unit" SET "evolvedName" = 'Commander Cat' WHERE "unitNumber" = 776;
UPDATE "Unit" SET "evolvedName" = 'Winter Commander Kaihime' WHERE "unitNumber" = 777;
UPDATE "Unit" SET "evolvedName" = 'Magical Cat☆ Magica' WHERE "unitNumber" = 778;
UPDATE "Unit" SET "evolvedName" = 'Salvation''s Daughter Lunacia' WHERE "unitNumber" = 779;
UPDATE "Unit" SET "evolvedName" = 'Dodgeballer Cat' WHERE "unitNumber" = 780;
UPDATE "Unit" SET "evolvedName" = 'Mamolan Pasalan' WHERE "unitNumber" = 781;
UPDATE "Unit" SET "evolvedName" = 'Superstar Koneko' WHERE "unitNumber" = 783;
UPDATE "Unit" SET "evolvedName" = 'True Killer Gross Cat' WHERE "unitNumber" = 785;
UPDATE "Unit" SET "evolvedName" = 'Illusionist Catman' WHERE "unitNumber" = 786;
UPDATE "Unit" SET "evolvedName" = 'Death''s Daughter Lunacia' WHERE "unitNumber" = 787;
UPDATE "Unit" SET "evolvedName" = 'Baki Hanma CC' WHERE "unitNumber" = 789;
UPDATE "Unit" SET "evolvedName" = 'Retsu Kaioh CC' WHERE "unitNumber" = 790;
UPDATE "Unit" SET "evolvedName" = 'Kaoru Hanayama CC' WHERE "unitNumber" = 791;
UPDATE "Unit" SET "evolvedName" = 'Katsumi Orochi CC' WHERE "unitNumber" = 792;
UPDATE "Unit" SET "evolvedName" = 'Jack Hammer CC' WHERE "unitNumber" = 793;
UPDATE "Unit" SET "evolvedName" = 'Ogre Cat Face' WHERE "unitNumber" = 794;
UPDATE "Unit" SET "evolvedName" = 'Li''l Baki CC' WHERE "unitNumber" = 795;
UPDATE "Unit" SET "evolvedName" = 'Baki Cat CC' WHERE "unitNumber" = 796;
UPDATE "Unit" SET "evolvedName" = 'Kaioh Cat CC' WHERE "unitNumber" = 797;
UPDATE "Unit" SET "evolvedName" = 'Doppo Cat CC' WHERE "unitNumber" = 798;
UPDATE "Unit" SET "evolvedName" = 'Grandiose Gunhauzer' WHERE "unitNumber" = 799;
UPDATE "Unit" SET "evolvedName" = 'Master of Logic Mewton' WHERE "unitNumber" = 801;
UPDATE "Unit" SET "evolvedName" = 'Sonic & Cat' WHERE "unitNumber" = 803;
UPDATE "Unit" SET "evolvedName" = 'Tails & Cat' WHERE "unitNumber" = 804;
UPDATE "Unit" SET "evolvedName" = 'Knuckles & Cat' WHERE "unitNumber" = 805;
UPDATE "Unit" SET "evolvedName" = 'Shadow & Cat' WHERE "unitNumber" = 806;
UPDATE "Unit" SET "evolvedName" = 'Sonic Cat CC' WHERE "unitNumber" = 807;
UPDATE "Unit" SET "evolvedName" = 'Tails Cat CC' WHERE "unitNumber" = 808;
UPDATE "Unit" SET "evolvedName" = 'Shadow Cat CC' WHERE "unitNumber" = 809;
UPDATE "Unit" SET "evolvedName" = 'Edgemaster Staal' WHERE "unitNumber" = 810;
UPDATE "Unit" SET "evolvedName" = 'Zeta Skanda' WHERE "unitNumber" = 811;
UPDATE "Unit" SET "evolvedName" = 'Tasmanian Giant Crab CC' WHERE "unitNumber" = 813;
UPDATE "Unit" SET "evolvedName" = 'Mass Production EVA-Cat' WHERE "unitNumber" = 814;
UPDATE "Unit" SET "evolvedName" = 'Moon Disciple Kaworu' WHERE "unitNumber" = 815;
UPDATE "Unit" SET "evolvedName" = 'Moririn' WHERE "unitNumber" = 817;
UPDATE "Unit" SET "evolvedName" = 'Rapper Cat' WHERE "unitNumber" = 819;
UPDATE "Unit" SET "evolvedName" = 'Seaside Pegasa v' WHERE "unitNumber" = 820;
UPDATE "Unit" SET "evolvedName" = 'Business Partner Cat' WHERE "unitNumber" = 822;
UPDATE "Unit" SET "evolvedName" = 'Flame Mage Sidmi' WHERE "unitNumber" = 824;
UPDATE "Unit" SET "evolvedName" = 'Cammy CC' WHERE "unitNumber" = 826;
UPDATE "Unit" SET "evolvedName" = 'Juri CC' WHERE "unitNumber" = 827;
UPDATE "Unit" SET "evolvedName" = 'Zangief Cat CC' WHERE "unitNumber" = 828;
UPDATE "Unit" SET "evolvedName" = 'Jamie Cat CC' WHERE "unitNumber" = 829;
UPDATE "Unit" SET "evolvedName" = 'Raclesa Σ' WHERE "unitNumber" = 830;
UPDATE "Unit" SET "evolvedName" = 'Lunos the Luminous' WHERE "unitNumber" = 837;

-- Fix formCount for units that don't have exactly 3 forms
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 27;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 28;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 29;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 45;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 53;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 59;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 62;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 64;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 65;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 73;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 75;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 76;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 82;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 108;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 110;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 112;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 113;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 114;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 115;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 116;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 117;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 118;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 131;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 135;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 137;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 138;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 140;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 141;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 158;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 175;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 176;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 177;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 181;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 184;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 186;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 189;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 190;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 200;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 202;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 212;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 214;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 215;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 216;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 217;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 218;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 219;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 220;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 221;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 229;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 230;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 242;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 243;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 244;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 269;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 274;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 277;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 278;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 279;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 280;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 290;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 291;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 292;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 293;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 294;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 295;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 296;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 297;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 298;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 301;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 304;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 305;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 306;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 315;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 317;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 318;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 326;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 327;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 328;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 333;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 342;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 343;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 346;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 354;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 359;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 360;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 361;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 363;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 364;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 365;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 366;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 367;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 368;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 371;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 372;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 373;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 374;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 375;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 378;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 380;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 381;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 384;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 386;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 387;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 388;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 389;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 397;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 399;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 400;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 403;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 404;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 406;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 407;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 408;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 411;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 412;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 415;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 416;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 418;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 419;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 420;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 421;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 428;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 429;
UPDATE "Unit" SET "formCount" = 4 WHERE "unitNumber" = 431;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 432;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 433;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 435;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 438;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 441;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 449;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 451;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 455;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 457;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 458;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 459;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 460;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 461;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 463;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 466;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 470;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 471;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 472;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 475;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 476;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 477;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 478;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 481;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 483;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 484;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 485;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 486;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 487;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 489;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 490;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 491;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 493;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 494;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 497;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 498;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 499;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 500;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 501;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 507;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 508;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 509;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 510;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 512;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 513;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 514;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 515;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 516;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 518;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 520;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 526;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 529;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 530;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 535;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 536;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 537;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 538;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 543;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 544;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 547;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 548;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 549;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 550;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 551;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 552;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 555;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 557;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 558;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 560;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 561;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 562;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 571;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 572;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 573;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 574;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 575;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 576;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 577;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 578;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 579;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 580;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 581;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 582;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 583;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 585;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 586;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 587;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 588;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 590;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 591;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 592;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 593;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 596;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 597;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 598;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 599;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 600;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 601;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 602;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 603;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 604;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 605;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 606;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 609;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 611;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 612;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 615;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 616;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 622;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 624;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 630;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 635;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 641;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 646;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 648;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 650;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 651;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 652;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 657;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 661;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 666;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 671;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 672;
UPDATE "Unit" SET "formCount" = 1 WHERE "unitNumber" = 673;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 677;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 678;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 679;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 680;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 681;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 686;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 687;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 689;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 690;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 693;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 695;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 696;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 699;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 705;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 708;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 709;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 710;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 711;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 718;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 719;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 721;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 722;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 725;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 726;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 727;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 728;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 731;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 735;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 736;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 737;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 738;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 740;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 741;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 742;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 743;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 744;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 745;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 746;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 747;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 748;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 749;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 750;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 751;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 752;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 753;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 754;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 756;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 758;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 759;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 760;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 763;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 767;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 768;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 769;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 771;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 772;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 773;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 774;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 776;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 777;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 778;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 779;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 780;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 781;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 783;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 785;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 786;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 787;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 789;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 790;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 791;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 792;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 793;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 794;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 795;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 796;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 797;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 798;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 799;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 801;
UPDATE "Unit" SET "formCount" = 1 WHERE "unitNumber" = 802;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 803;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 804;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 805;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 806;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 807;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 808;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 809;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 810;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 811;
UPDATE "Unit" SET "formCount" = 1 WHERE "unitNumber" = 812;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 813;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 814;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 815;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 817;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 819;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 820;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 822;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 824;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 826;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 827;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 828;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 829;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 830;
UPDATE "Unit" SET "formCount" = 2 WHERE "unitNumber" = 837;
