-- Fix unit names using Black Catculator 3.1.15 as authoritative source
-- Corrects names where form2 was concatenated, formatting was wrong,
-- or abbreviated names needed expanding

UPDATE "Unit" SET "name" = 'Mr.' WHERE "unitNumber" = 11;
UPDATE "Unit" SET "name" = 'Nekoluga' WHERE "unitNumber" = 34;
UPDATE "Unit" SET "name" = 'Sodom' WHERE "unitNumber" = 83;
UPDATE "Unit" SET "name" = 'Megidora' WHERE "unitNumber" = 84;
UPDATE "Unit" SET "name" = 'Vars' WHERE "unitNumber" = 85;
UPDATE "Unit" SET "name" = 'Kamukura' WHERE "unitNumber" = 86;
UPDATE "Unit" SET "name" = 'Raiden' WHERE "unitNumber" = 87;
UPDATE "Unit" SET "name" = 'Neneko' WHERE "unitNumber" = 131;
UPDATE "Unit" SET "name" = 'Kung Fu Cat X' WHERE "unitNumber" = 132;
UPDATE "Unit" SET "name" = 'Momotaro' WHERE "unitNumber" = 136;
UPDATE "Unit" SET "name" = 'Princess Kaguya' WHERE "unitNumber" = 138;
UPDATE "Unit" SET "name" = 'Baby Mola' WHERE "unitNumber" = 173;
UPDATE "Unit" SET "name" = 'Meowla Meowla' WHERE "unitNumber" = 175;
UPDATE "Unit" SET "name" = 'Dioramos' WHERE "unitNumber" = 177;
UPDATE "Unit" SET "name" = 'Takuya ＆ Yuki' WHERE "unitNumber" = 179;
UPDATE "Unit" SET "name" = 'Mr. Ninja' WHERE "unitNumber" = 184;
UPDATE "Unit" SET "name" = 'Akira' WHERE "unitNumber" = 194;
UPDATE "Unit" SET "name" = 'Mekako Saionji' WHERE "unitNumber" = 195;
UPDATE "Unit" SET "name" = 'Catman' WHERE "unitNumber" = 196;
UPDATE "Unit" SET "name" = 'Psychocat' WHERE "unitNumber" = 197;
UPDATE "Unit" SET "name" = 'Kachi-Kachi' WHERE "unitNumber" = 203;
UPDATE "Unit" SET "name" = 'Catburger' WHERE "unitNumber" = 213;
UPDATE "Unit" SET "name" = 'Pumpcat' WHERE "unitNumber" = 227;
UPDATE "Unit" SET "name" = 'Freshman Cat Jobs' WHERE "unitNumber" = 237;
UPDATE "Unit" SET "name" = 'Rich Cat III' WHERE "unitNumber" = 238;
UPDATE "Unit" SET "name" = 'Radiant Aphrodite' WHERE "unitNumber" = 259;
UPDATE "Unit" SET "name" = 'Catway' WHERE "unitNumber" = 260;
UPDATE "Unit" SET "name" = 'Hayabusa' WHERE "unitNumber" = 261;
UPDATE "Unit" SET "name" = 'Fortressy' WHERE "unitNumber" = 280;
UPDATE "Unit" SET "name" = 'Mighty Kat-A-Pult' WHERE "unitNumber" = 304;
UPDATE "Unit" SET "name" = 'Mighty Bomburr' WHERE "unitNumber" = 306;
UPDATE "Unit" SET "name" = 'Yuletide Nurse' WHERE "unitNumber" = 310;
UPDATE "Unit" SET "name" = 'Years-End Neneko' WHERE "unitNumber" = 314;
UPDATE "Unit" SET "name" = 'PIKOTARO' WHERE "unitNumber" = 315;
UPDATE "Unit" SET "name" = 'CPAC' WHERE "unitNumber" = 317;
UPDATE "Unit" SET "name" = 'Mobius' WHERE "unitNumber" = 326;
UPDATE "Unit" SET "name" = 'Belial' WHERE "unitNumber" = 327;
UPDATE "Unit" SET "name" = 'Happy 100' WHERE "unitNumber" = 328;
UPDATE "Unit" SET "name" = 'Bunny & Canard' WHERE "unitNumber" = 331;
UPDATE "Unit" SET "name" = 'Trickster Himeyuri' WHERE "unitNumber" = 334;
UPDATE "Unit" SET "name" = 'Wolfchild Deale' WHERE "unitNumber" = 357;
UPDATE "Unit" SET "name" = 'Graveflower Verbena' WHERE "unitNumber" = 358;
UPDATE "Unit" SET "name" = 'Satori Hikami & Cat' WHERE "unitNumber" = 384;
UPDATE "Unit" SET "name" = 'Sakura Sonic' WHERE "unitNumber" = 397;
UPDATE "Unit" SET "name" = 'Shinji & Cat' WHERE "unitNumber" = 402;
UPDATE "Unit" SET "name" = 'Gendo & Fuyutsuki Cats' WHERE "unitNumber" = 403;
UPDATE "Unit" SET "name" = 'Kaworu & Cat' WHERE "unitNumber" = 405;
UPDATE "Unit" SET "name" = 'Rei Ayanami' WHERE "unitNumber" = 409;
UPDATE "Unit" SET "name" = 'Asuka Langley' WHERE "unitNumber" = 410;
UPDATE "Unit" SET "name" = 'Mari Illustrious' WHERE "unitNumber" = 411;
UPDATE "Unit" SET "name" = 'Eva Unit-00' WHERE "unitNumber" = 412;
UPDATE "Unit" SET "name" = 'Eva Unit-01' WHERE "unitNumber" = 413;
UPDATE "Unit" SET "name" = 'Eva Unit-02' WHERE "unitNumber" = 414;
UPDATE "Unit" SET "name" = 'Moon Operators' WHERE "unitNumber" = 416;
UPDATE "Unit" SET "name" = 'Otaku Geek Cat' WHERE "unitNumber" = 429;
UPDATE "Unit" SET "name" = 'Betakkuma' WHERE "unitNumber" = 432;
UPDATE "Unit" SET "name" = 'Nekokkuma' WHERE "unitNumber" = 433;
UPDATE "Unit" SET "name" = 'Empress Chronos' WHERE "unitNumber" = 439;
UPDATE "Unit" SET "name" = 'Ushiwakamaru' WHERE "unitNumber" = 451;
UPDATE "Unit" SET "name" = 'Kotomine & Gilgamesh Cats' WHERE "unitNumber" = 460;
UPDATE "Unit" SET "name" = 'Legeluga' WHERE "unitNumber" = 461;
UPDATE "Unit" SET "name" = 'Filibuster Cat X' WHERE "unitNumber" = 462;
UPDATE "Unit" SET "name" = 'Super Zeus' WHERE "unitNumber" = 467;
UPDATE "Unit" SET "name" = 'Super Devil' WHERE "unitNumber" = 469;
UPDATE "Unit" SET "name" = 'Satanmaria' WHERE "unitNumber" = 470;
UPDATE "Unit" SET "name" = 'Heracrist' WHERE "unitNumber" = 471;
UPDATE "Unit" SET "name" = 'Lumina' WHERE "unitNumber" = 478;
UPDATE "Unit" SET "name" = 'Benevolent Souma' WHERE "unitNumber" = 482;
UPDATE "Unit" SET "name" = 'Kano ＆ Souma' WHERE "unitNumber" = 483;
UPDATE "Unit" SET "name" = 'Eva Unit-08' WHERE "unitNumber" = 487;
UPDATE "Unit" SET "name" = 'Rei Ayanami (???)' WHERE "unitNumber" = 491;
UPDATE "Unit" SET "name" = 'Relentless Gladios' WHERE "unitNumber" = 505;
UPDATE "Unit" SET "name" = 'Mightycat' WHERE "unitNumber" = 507;
UPDATE "Unit" SET "name" = 'Lasvoss' WHERE "unitNumber" = 519;
UPDATE "Unit" SET "name" = 'Urs & Fenrir' WHERE "unitNumber" = 532;
UPDATE "Unit" SET "name" = 'Kagamine Rin & Len' WHERE "unitNumber" = 537;
UPDATE "Unit" SET "name" = 'The 4th Angel' WHERE "unitNumber" = 548;
UPDATE "Unit" SET "name" = 'The 6th Angel' WHERE "unitNumber" = 549;
UPDATE "Unit" SET "name" = 'The 10th Angel' WHERE "unitNumber" = 550;
UPDATE "Unit" SET "name" = 'The 9th Angel' WHERE "unitNumber" = 551;
UPDATE "Unit" SET "name" = 'MEIKO & Cat' WHERE "unitNumber" = 561;
UPDATE "Unit" SET "name" = 'Hatsune Miku: MM2020 Osaka' WHERE "unitNumber" = 582;
UPDATE "Unit" SET "name" = 'Hatsune Miku: MM2020 Tokyo' WHERE "unitNumber" = 583;
UPDATE "Unit" SET "name" = 'Sweet Aphrodite' WHERE "unitNumber" = 587;
UPDATE "Unit" SET "name" = 'Kaito & Cat' WHERE "unitNumber" = 591;
UPDATE "Unit" SET "name" = 'Ranma Saotome (M)' WHERE "unitNumber" = 596;
UPDATE "Unit" SET "name" = 'Ryoga Hibiki (Pig)' WHERE "unitNumber" = 598;
UPDATE "Unit" SET "name" = 'Shampoo (Cat)' WHERE "unitNumber" = 599;
UPDATE "Unit" SET "name" = 'Mousse (Duck)' WHERE "unitNumber" = 600;
UPDATE "Unit" SET "name" = 'Ukyo Kuonji (GR)' WHERE "unitNumber" = 602;
UPDATE "Unit" SET "name" = 'Tatewaki Kuno (Gi)' WHERE "unitNumber" = 603;
UPDATE "Unit" SET "name" = 'Ranma Cat (M)' WHERE "unitNumber" = 604;
UPDATE "Unit" SET "name" = 'Summoner Satoru' WHERE "unitNumber" = 617;
UPDATE "Unit" SET "name" = 'Aku Researcher' WHERE "unitNumber" = 621;
UPDATE "Unit" SET "name" = 'Kunio-kun' WHERE "unitNumber" = 624;
UPDATE "Unit" SET "name" = 'Mighty Deth-Troy-R' WHERE "unitNumber" = 632;
UPDATE "Unit" SET "name" = 'Ancient Egg: N101' WHERE "unitNumber" = 658;
UPDATE "Unit" SET "name" = 'Ancient Egg: N102' WHERE "unitNumber" = 659;
UPDATE "Unit" SET "name" = 'Ancient Egg: N103' WHERE "unitNumber" = 663;
UPDATE "Unit" SET "name" = 'Ancient Egg: N104' WHERE "unitNumber" = 664;
UPDATE "Unit" SET "name" = 'Ancient Egg: N201' WHERE "unitNumber" = 665;
UPDATE "Unit" SET "name" = 'Ancient Egg: N003' WHERE "unitNumber" = 669;
UPDATE "Unit" SET "name" = 'Ancient Egg: N202' WHERE "unitNumber" = 670;
UPDATE "Unit" SET "name" = 'Ranma Saotome (Leotard)' WHERE "unitNumber" = 671;
UPDATE "Unit" SET "name" = 'Genma Saotome (Panda)' WHERE "unitNumber" = 672;
UPDATE "Unit" SET "name" = 'Ancient Egg: N105' WHERE "unitNumber" = 675;
UPDATE "Unit" SET "name" = 'Ancient Egg: N106' WHERE "unitNumber" = 676;
UPDATE "Unit" SET "name" = 'Osamu Mikumo & Cat' WHERE "unitNumber" = 677;
UPDATE "Unit" SET "name" = 'Yuma Kuga & Cat' WHERE "unitNumber" = 678;
UPDATE "Unit" SET "name" = 'Chika Amatori & Cat' WHERE "unitNumber" = 679;
UPDATE "Unit" SET "name" = 'Ancient Egg: N004' WHERE "unitNumber" = 685;
